### ISSUE TITLE
Apphooks should be loaded on unpublished pages

### ISSUE THREAD

**Issue by yakky** [django-cms/django-cms#2605]
This allows editing an application hooked to a page behind the curtains, otherwise editor can't interact with application data unless page is published.
@digi604 any comment on this?

**Comment by marcinn** [comment]
These changes will improve faulty apphooks design:

1. apphooks should be always loaded, when server starts, even if no apphook is bound to any page (published or not)
2. there may be an table with enabled apphooks to dynamically enable/disable selected (see how Trac plugins works, just get this idea and implement); after enabling/disabling server should be restarted, but not after adding or removing a page (!); this is not same as removing app from INSTALLED_APPS
3. when page_url can't resolve page by slug, a "empty" link should be returned, because page_url is related to dynamic content, but may be used in a static area (i.e. layout of the page); this should work same as no variable defined in template until you enable strict template debug in your settings. 

Thanks.

**Comment by yakky** [comment]
The idea of apphooks is to plug directly in django urlconf to be a zero-overhead solution to dynamic application hookin
Thus you can't load an apphook, if you don't know in which part of the tree it should attached to.
That's the reason for the reload when publishing the page (this is anyhow solved in 3.2 thanks to the reload middleware)
I can't understand what you mean at point 3

**Comment by marcinn** [comment]
> you can't load an apphook, if you don't know in which part of the tree it should attached to

Maybe this a casue of faulty design (in the context of url resolvers). 

 > this is anyhow solved in 3.2 thanks to the reload middleware

No, this is not a solution. System without apphook loaded still throws an exception. Apphook can't be loaded, because there is no published page with that app. The design should be changed instead of implementing workarounds.

> can't understand what you mean at point 3

Base template may contain `{% page_url %}` tags with slugs set to undefined/unpublished/non-existent pages. Whole app goes down by raising an exception. Have you tried to add a page using in-page editor when exception was raised and traceback is shown?

**Comment by darkowic** [comment]
Hello there! What about this issue?

I definitely agree with @yakky opinion. I'm new in django cms and I already wasted an hour (btw if I read the documentation more carefully I could avoid it... http://docs.django-cms.org/en/release-3.4.x/how_to/apphooks.html#using-an-apphook) wondering why my app's urls aren't included. Reading source I found that we do not include not published pages...
```
# appresolver.py _get_app_patterns
    # we don't have a request here so get_page_queryset() can't be used,
    # so use public() queryset.
    # This can be done because url patterns are used just in frontend

    title_qs = Title.objects.public().filter(page__site=current_site)
```
IMHO this is wrong. This disallows admin to edit page before publishing. Can't we check if the page is published or not at some higher level? Thanks to it we can avoid reloading server too, right?

**Comment by yakky** [comment]
@Aiky30 yes, unfortunately it's still an issue

**Comment by Aiky30** [comment]
@yakky OK, no problem, one to discuss on priority and plan for a fix.

**Comment by Aiky30** [comment]
Does anyone here want to open a PR with a proposed fix? Ideally with tests to prove disprove the functionality!
