### ISSUE TITLE
incorrect logging configuration 

### ISSUE THREAD

**Issue by techdragon** [django-cms/django-cms#3094]
this commit https://github.com/divio/django-cms/commit/438e66cce0a5d0d87aac1b2ca080fd80a22ba4d4
appears to have been the root cause of output i see in my console which is making it harder to debug a third party app thats plugging into the menu system via app hook.

`No handlers could be found for logger "menus"`

adding something like this to the logger settings in the django app brings the errors to the surface, but the fact the errors were hidden when debug = True was most frustrating.

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console':{
                'level': 'DEBUG',
                'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        'menus': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
}
```

**Comment by FinalAngel** [comment]
@yakky or @mkoistinen what would be the state here?

**Comment by yakky** [comment]
I think we should just document that the menu emits logging messages on a specified logger. Which is on purpose, to avoid spamming logs for no good reason

**Comment by Aiky30** [comment]
Hello @techdragon,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
