### ISSUE TITLE
Improve documentation on how to unit tests apphooks

### ISSUE THREAD

**Issue by johnraz** [django-cms/django-cms#3153]
it's really not straightforward to know how to test an apphook in a custom project.
Providing a short explanation and maybe a dedicated TestCase could help too. Or at least add some doc to the existing tests, so people can get their inspiration from there.

**Comment by lddubeau** [comment]
@yakky Testing only the application's logic is a risky proposition. 

I'm currently integrating django-cms to a project that has been up and running for months without django-cms. I initially followed the urlconf approach to test an app which I converted to use with django-cms. Approximately 90% of the tests passed. Some failed because I had set the tests to operate like a user would, by following the navigation menus. I realized that the apphook method does not replicate the menu system so I used the `create_page` approach that johnraz mentioned earlier. After I got the whole thing to work as I wanted, I discovered that some tests were still failing because **I had a bug in my menus**. If I had modified my test suite so that it would run by using the urlconf method (which was doable), I would not have caught the menu bug. Sure, my Selenium-based test suite would have found the problem but the Selenium tests are much more expensive to run than the tests based on `unittest`.

At any rate, I got the `create_page` approach to work for me by doing the following:

```
        self.lexicography_page = \
            create_page("Lexicography", "generic_page.html",
                        "en-us", created_by=self.admin,
                        apphook='LexicographyApp')
        self.lexicography_page.toggle_in_navigation()
        self.lexicography_page.publish('en-us')
        from menus.menu_pool import menu_pool
        menu_pool.clear(all=True)
        from cms.appresolver import clear_app_resolvers
        clear_app_resolvers()
```

The `toggle_in_navigation()` bit is necessary so that the page shows up in the menu. I found clearing the `menu_pool` necessary to avoid stale menus. The call to `clear_app_resolvers()` is also necessary to prevent the CMS middleware from raising `DoesNotExist: Page matching query does not exist.` Without it, the first test would pass but all subsequent tests would fail. Upon debugging I found that Django CMS got out of sync regarding the `id` values actually in the database and what the ids that were returned by the resolvers in `cms.appresolver.APP_RESOLVERS`.

**Comment by FinalAngel** [comment]
@yakky any update here or will this be postponed for 3.3?
