### ISSUE TITLE
graceful plugin exceptions

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-cms#3157]
Sometimes a plugin can cause an exception based on whatever is entered by the user, or because of other causes (e.g an api that is unreachable). Obviously this is a bug in the plugin, but it can happen and it can happen on production servers. Currently we let the exception bubble up and show a 500 page. In production this is a desaster, because with frontend editing, you can't even navigate the the page and remove the offending plugin anymore. The user is completely blocked concerning that page and has to get a developer to fix the bug before any more content can be entered on the page.

I propose that plugin rendering for each plugin has a try/except around it. To Visitors the offending plugin should just not be rendered (or an error message?). To content editors the plugin should be rendered in a way that is clear that something went wrong (perhaps with a red border and a message in the notification area at the top of the screen). In structure view the plugin should also be highlighted. In any case it should be possible to still edit or remove the plugin.
In any case the error should be logged with a traceback.

This behaviour should be controlled by a new setting that uses `DEBUG` as a default but can be overridden.

**Comment by sidneijp** [comment]
Hi,

For those who can't wait for a release that fix it, we've develop a simple workaround for it. It basically dynamically decorates all registered plugins' `render` method to handle exceptions with a default fallback template (configurable). We recommend to call it just after `django.setup` in `project/wsgi.py`.

\<project\>/decorators.py
```
# coding: utf-8

from django.conf import settings
from functools import wraps
import logging
import traceback

logger = logging.getLogger(__name__)


def get_render_template(context, instance, placeholder):
    """Returns configured default template to show on plugins rendering exceptions"""
    return getattr(settings, 'CMS_PLUGIN_RENDER_ERROR_TEMPLATE', 'cms/render_plugin_error.html')


def plugin_exception_handler(func):
    """Decorates plugin's `render` method to set a default template as fallback
    for exceptions when rendering it. It prevents the whole page from break cause
    of a faulty plugin."""
    global get_render_template

    @wraps(func)
    def wrapper(self, *args, **kwargs):
        try:
            result = func(self, *args, **kwargs)
        except Exception, ex:
            logger.error(self.__class__)
            traceback.print_exc()
            logger.exception(ex)
            self.get_render_template = get_render_template
            result = {}
        return result
    return wrapper
```

\<project\>/utils.py
```
# coding: utf-8

def wrap_plugins_render_method(decorator):
    """Wraps all plugins' `render` method with `decorator`"""
    from cms.plugin_pool import plugin_pool
    for plugin in plugin_pool.plugins.values():
        plugin.render = decorator(plugin.render)
```

\<project\>/wsgi.py
```
import os
import django
from django.core.handlers.wsgi import WSGIHandler
from utils import wrap_plugins_render_method
from decorators import plugin_exception_handler

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")


def get_wsgi_application():
    django.setup()
    
    # The important part here!!! 
    wrap_plugins_render_method(plugin_exception_handler)
    
    return WSGIHandler()

application = get_wsgi_application()
```

\<project\>/settings.py
```
...
# Put it wherever you like
CMS_PLUGIN_RENDER_ERROR_TEMPLATE = 'cms/render_plugin_error.html'
...
```

\<project\>/templates/cms/render_plugin_error.html
```
Fallback template for faulty plugins
```

I hope it helps someone as it did for us. Enjoy.

**Comment by Aiky30** [comment]
@stefanfoulis, @sidneijp,

Hello {Name}

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
