### ISSUE TITLE
agree on and document a naming convention for plugin models and classes

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-cms#3204]
Especially for beginners it can be very confusing if the plugin model and the plugin base have the same name. And problems like http://stackoverflow.com/questions/20334029/django-app-cannot-assign-imagetext-link-must-be-a-link-instance arise, which could be avoided if we have one naming standard.
Since we don't have a recommended, documented way of doing things there are all sorts of variations out in the wild.
### Plugin Models (`models.py`):

``` python
from cms.models import CMSPlugin
class TextPlugin(CMSPlugin):
    title = models.CharField(max_length=255)
    body = models.TextField(blank=True, default='')
```
### Plugins (`cms_plugins.py`):

``` python
from cms.plugin_base import CMSPluginBase
class Text(CMSPluginBase):
    model = TextPlugin
    render_template = '....'
```

**Comment by stefanfoulis** [comment]
What I've been doing lately:

in ``models.py``:

```python
class FoobarCMSPlugin(CMSPlugin):
    cmsplugin_ptr = models.OneToOneField(CMSPlugin, related_name='+', parent_link=True)
    foo = models.BooleanField()
```
Setting ``related_name='+'`` prevents name clashes, because it simply does not add the reverse relation on the parent plugin. It might make sense to make this the default in cms core.

in ``cms_plugins.py``:
```python
from cms.plugin_base import CMSPluginBase
from . import models
class MyAppFoobarCMSPlugin(CMSPluginBase):
    name = _('Foobar')
    model = models.FoobarCMSPlugin
```
Prefixing the plugin name with the App name is necessary to avoid name clashes if multiple different apps use the same name. This will no longer be necessary once #2562 is fixed.
And I've been following the convention of naming the Model and the Plugin the same (except for the prefix workaround mentioned above)  and then importing the module rather than individual Models.

What do you think?

**Comment by evildmp** [comment]
I always call my classes *Editor* and *Publisher* - as in:

* ``BlackmailLetterPluginEditor`` - the model that the user configures
* ``BlackmailLetterPluginPublisher`` - the CMSPluginBase subclass

Its not brilliant, because any admin code needs to go into the  ``BlackmailLetterPluginPublisher``, which seems a bit weird, but it's better than ``ThingPlugin`` and ``ThingPluginModel`` which is hopeless.

**Comment by yakky** [comment]
@stefanfoulis @evildmp I'm not super happy with any proposed naming convention, but anyone is actually better than none.
I like the idea of the related_name thing into core. Opening a separate issue for it


Removing the blocker tag

**Comment by czpython** [comment]
I also like the related_name approach in core, however doing this will break backwards compatibility so we should be careful.

And regarding naming conventions I usually create models prefixed with Plugin, so if it's a carousel for example the model would look like ```CarouselPlugin``` and the plugin class in ```cms_plugins.py``` would look like ```Carousel```. I do this because in my head, you will only find plugin classes in cms_plugins.py so no need to prefix them with something like Plugin but in a models.py you could have other models that are not really plugins that's why I do the Plugin prefix there.

**Comment by yakky** [comment]
@stefanfoulis @evildmp so the agreed convention is:

 * ``SomePlugin``: the plugin model
 * ``CMSSomePlugin``: the plugin class

This must be documented and the examples in the docs must be changed accordingly

**Comment by johnraz** [comment]
Ha \o/ finally :-)

**Comment by FinalAngel** [comment]
@evildmp are you able to document this for 3.2?

**Comment by jakob-o** [comment]
Hey,

I checked our code base and we use `MyPlugin` and `MyPluginModel` for the plugin and it's plugin model respectively. It may not be too beautiful, but it is clear what is meant when you are talking about the concepts of plugin and plugin model which where introduced and will likely stick around. So for anyone who does not know the documentation by heart it is impossible to deduce whether the CMS prefix is identifying the plugin or it's model. So for the sake of simplicity and clarity I would prefer the `Plugin` and `PluginModel` suffixes over any other. Think of all the time and pain saved for sacrificing the a-model-suffix-is-not-beautiful argument.

My two cents

Jakob
