### ISSUE TITLE
Placeholder doesn't respect limits

### ISSUE THREAD

**Issue by ar4s** [django-cms/django-cms#3207]
I set global limit to placeholder in `settings.py`, something like this:

```
CMS_PLACEHOLDER_CONF = {
 'slider': {
        'name': gettext('slider'),
        'plugins': ['SliderPlugin'],
        'limits': {
            'global': 1,
        },
    },
}
```

in edit mode I can add only one slider plugin but I can copy from another language - placeholder doesn't respect limit.

**Comment by yakky** [comment]
@ar4s is this still valid in latest 3.0.10?

**Comment by yakky** [comment]
@mkoistinen easily reproducible. I think this should fit into 3.0.11

**Comment by mkoistinen** [comment]
I am pretty sure I have reported this one myself months ago..., however, it needs more attention span that we have for 3.0.11.

**Comment by Aiky30** [comment]
I have seen issues reported regarding limits in the past although it's possible that this was a child plugin limit issue and not a placeholder issue. If nothing is reported in this issue in the next 30 days it will be closed.

**Comment by Aiky30** [comment]
Hello @ar4s,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
