### ISSUE TITLE
Add documentation for PlaceholderPlugin & AliasPlugin

### ISSUE THREAD

**Issue by o-zander** [django-cms/django-cms#3335]
I have a very strict placeholder config and as I first used the copy all function I thought it was broken. I then realised I have to add PlaceholderPlugin to my placeholder config. Same goes with the AliasPlugin. As they are core plugins the check against the config should be skipped for this plugins. It would be a good idea to check against the config for the plugins they are containing. It makes no sense that I add the placeholder plugin to every placeholders allowed plugins and then the placeholder plugin adds plugins that aren't allowed in this specific placeholder. 
So at first this problem should be mentioned in documentation but later the whole mechanism should be improved.

**Comment by FinalAngel** [comment]
@evildmp would you be able to document this?

**Comment by czpython** [comment]
I believe this has been fixed now (>= 3.4.x)

**Comment by Aiky30** [comment]
Hello @o-zander,

The future vision of the CMS is to not contain any core plugins to make the core much simpler going forward.

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
