### ISSUE TITLE
menu_tags context's stack bug

### ISSUE THREAD

**Issue by DylannCordel** [django-cms/django-cms#3432]
Because context.update add a new level in the Context's stack and because there is never a context.pop called in menu_tags, the context AFTER a menu_tags call is not the same than BEFORE the call and there is some funny.
## How to reproduce

onecolum.html :

```
<h1>Dolly vs Magic Pony Fight</h1>
{% block main %}
<div id="maincolumn">some content</div>
{% endblock %}
```

twocolumns.html :

```
{% extends "one_olumn.html" %}
{% load menu_tags %}
{% block main %}
    {% with template='Magic Pony is the best !' %}
        <h2>{{ template }}</h2>
        {% block sidebar %}
            <aside>
                But Dolly could be a problem !
                {% show_sub_menu 1 %}
                <h2>{{ template }}</h2>
            </aside>
        {% endblock %}
        {{ block.super }}
    {% endwith %}
{% endblock %}
```
### Expected Result

When twocolumns.html is rendered, we should have :

```
<h1>Dolly vs Magic Pony Fight</h1>
<h2>Magic Pony is the best !</h2>
<aside>
    But Dolly could be a problem !
    <h2>Magic Pony is the best !</h2>
</aside>
<div id="maincolumn">some content</div>
```
### Current Result

But when twocolumns.html is rendered, we currently have :

```
<h1>Dolly vs Magic Pony Fight</h1>
<h2>Magic Pony is the best !</h2>
<aside>
    But Dolly could be a problem !
    <h2>menu/sub_menu.html</h2>
</aside>
<aside>
    But Dolly could be a problem !
    <h2>menu/sub_menu.html</h2>
</aside>
```

A PR is in WIP : #3431

**Need help (and time... :-(... ) for this one plz. See [this comment](https://github.com/divio/django-cms/pull/3431#issuecomment-54474801)**

A workaround for the "block.super" if you have this problem and can't wait his correction : surround the block containing <code>{{ block.super }}</code> by <code>{% with super=block.super %}</code> and replace <code>{{ block.super }}</code> by <code>{{ super }}</code>.

**Comment by FinalAngel** [comment]
@DylannCordel sorry for the very late response :( Is this still relevant to you?

**Comment by Aiky30** [comment]
Hello @DylannCordel,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
