### ISSUE TITLE
Support for tag "endrender_placeholder"

### ISSUE THREAD

**Issue by Darkless012** [django-cms/django-cms#3510]
Would it be possible to add support for tag:
_endrender_placeholder_
Eg. to have option to render another text if the placeholder is empty.

```
{% render_placeholder "model_text" or %}There is no content.{% endrender_placeholder %}
```

**Comment by Aiky30** [comment]
This is still a valid issue, there is no end render_placeholder tag. @Darkless012 @ojii Would either of you be interested in implementing this with the idea of taking it into a near future release?

**Comment by Aiky30** [comment]
Hello @Darkless012,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
