### ISSUE TITLE
Allow page extensions to hook into 'advanced settings' form?

### ISSUE THREAD

**Issue by ojii** [django-cms/django-cms#3566]
Right now, Page Extensions need a separate toolbar menu item to be editable. However, from a site operators perspective, many of the fields in Page Extensions might be more logically grouped under 'advanced settings'.

Should we add an API to allow Page Extensions to hook into advanced settings?

/cc @evildmp @czpython @mkoistinen @digi604 @stefanfoulis @yakky 

See https://botbot.me/freenode/django-cms/2014-11-06/?msg=24973849&page=2 for IRC conversation.

**Comment by marksweb** [comment]
I was trying to add to the `PageAdmin` after seeing a SO answer & blog post making it look as though adding to `PageAdmin.inlines` was possible - see #3763 

I've recently had a client request to drop a menu in to a page to display it's children regardless of if those pages are hidden from menus. So I wanted to add a simple checkbox & text field to the page settings menu so that it was simple while you were setting up the page.

**Comment by macolo** [comment]
Wow. I am surprised not more people want this. I find the UX of the Page Menu solution less than satisfactory. People search for fields in the page settings first.

Is there really no way to add some fields to the advanced page form?

**Comment by Uznick** [comment]
I agree, it's rather important usability feature.

**Comment by digiology** [comment]
+1 for this feature, it would be really handy for us. 

Ross R.

**Comment by pau1a** [comment]
+1
