### ISSUE TITLE
Root menu 'show_menu' offset

### ISSUE THREAD

**Issue by doctormo** [django-cms/django-cms#3598]
We had a recent problem where a new editor in the cms accidentally clicked the 'show in menu' option for the root of our website (https://inkscape.org) this caused the menu cache to slowly replace the menu with all the entries from the next level.

This menu was so easy to break and caused such large problems that I really want to lock that record field away, because it's horrid. But I thought I'd better report the experence here, in case there's any code solution that could be brought when it comes to the menu system. It'd be nice to be able to say 'root' or 'soft-root' or which ever as the originator for the menu despite what the show_in_menu option says.

(in fact the show in menu item might not be applicable to the root IMO)

**Comment by FinalAngel** [comment]
closed in fafour of https://github.com/divio/django-cms/issues/3598

**Comment by Aiky30** [comment]
Hello @doctormo,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
