### ISSUE TITLE
Automated check that PlaceholderFields use PlaceholderAdminMixin

### ISSUE THREAD

**Issue by jsma** [django-cms/django-cms#3734]
Haven't looked into the feasibility of this but would like for the checks framework to detect all models with PlaceholderField, if any of those models are also registered in the admin that the admin class inherits from PlaceholderAdminMixin. It's an error to ever do otherwise, so would like this to be loud instead of silent.

**Comment by yakky** [comment]
That would be a nice addition.
It's definitely feasible by getting all the models with the Django API, checking if any field is a PlaceholderField and then getting the related model from the admin registry and checking the mro() method result

**Comment by FinalAngel** [comment]
@jsma would you be able to open a pull request that addresses this issue?

**Comment by Aiky30** [comment]
Hello @jsma,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
