### ISSUE TITLE
render static placeholder without edit mode

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#3757]
I think it makes sense to add an option to the `static_placeholder` tag to render the placeholder without the edit capabilities, in other words disable the edit mode for this one static placeholder.
@yakky @mkoistinen  thoughts ?

**Comment by mkoistinen** [comment]
What would be the use-case?

**Comment by yakky** [comment]
Probably a permission based approach is more sensible here, if I understand correctly the underline use case

**Comment by czpython** [comment]
well the use case at the moment is we use the static placeholder to render a menu bar (completely customized) and we display this menu in mobile and desktop and so need to render this static placeholder twice in the same template but on different html containers (one hidden by default), problem is that on edit mode both static placeholders will render the toolbar thus causing conflicts and results in neither of the two being modifiable.

**Comment by yakky** [comment]
Looks like a valid use-case to me

**Comment by yakky** [comment]
@ojii @evildmp what's your opinion?

**Comment by philippze** [comment]
It's easy to switch off front-end editing for a CMSPlugin. Give the `frontend_edit_template` the same value as the `render_template`. Probably this makes changes to the placeholder redundant.

**Comment by ojii** [comment]
use case sounds sane.

**Comment by mkoistinen** [comment]
We already have a related capability with {% render_placeholder ... as ... %}, this allows us to render a placeholder to a var, which can then be displayed without edit capabilities. Can this not be used?

**Comment by ojii** [comment]
I think this is about ``static_placeholder``. Also ``render_placeholder ... as`` disables edit mode?

**Comment by czpython** [comment]
Yes this is about ```static_placeholder``` and afaik ```render_placeholder ... as``` does not disable edit mode :)

**Comment by mkoistinen** [comment]
I'm pretty sure it does. And I think this should be implemented in a consistent manner manner.

**Comment by dkellner** [comment]
We've exactly the same use case as described in https://github.com/divio/django-cms/issues/3757#issuecomment-70160006 .

My current workaround is to just hide the second instance for logged in users. This is surely not the right thing to do in every case, but maybe it will help somebody else stumbling on this:
```
{% if not request.user.is_authenticated %}
  {% static_placeholder "main-navigation" %}
{% else %}
  <p>
    Due to a bug this navigation is only visible when you're
    <em>not</em> logged in.
  </p>
{% endif %}
```

**Comment by bartTC** [comment]
> It's easy to switch off front-end editing for a CMSPlugin. Give the frontend_edit_template the same value as the render_template. Probably this makes changes to the placeholder redundant.

Side note; this advice is marked as deprecated in v3.4 :

```
          warnings.warn(
                "Attribute `frontend_edit_template` will be removed in django CMS 3.5",
                PendingDeprecationWarning
            )
```

**Comment by bartTC** [comment]
FWIW here's my eventual solution: I figured that the `render_placeholder` does have a `editable` attribute but I couldn't overwrite it from the template level, I ended up having a separate render template tag that disables editing:

```
from cms.templatetags.cms_tags import RenderPlaceholder
from django import template

register = template.Library()


@register.tag('render_placeholder_noedit')
class RenderPlaceholderNoEdit(RenderPlaceholder):
    """
    Render the content of the plugins but without editing functionality.
    """
    name = 'render_placeholder_noedit'

    def _get_value(self, context, editable=True, **kwargs):
        return super(RenderPlaceholderNoEdit, self)._get_value\
            (context, editable=False, **kwargs)

# template
{% render_placeholder_noedit "placeholder_name" language "en" %}
```

**Comment by Aiky30** [comment]
Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
