### ISSUE TITLE
solid_i18_patterns in breadcrumbs

### ISSUE THREAD

**Issue by pawelmarkowski** [django-cms/django-cms#3813]
I have found issue in breadcrumbs. If you are using solid_i18n_patterns you are receiving in link main language code (which in solid i18 is abandoned) what results 404 error page. BTW link in menu is correct.

**Comment by yakky** [comment]
Apparently solid_i18n_patterns breaks a lot of assumptions django CMS does in page urls. I am not sure we can make it compatible with django CMS

**Comment by pawelmarkowski** [comment]
in admin panel I am receiving correct url. In breadcrumbs url is correct but when you switch to page edition you are seeing message. This site do not have preview. Redirection /LANG-PREFIX/url...

URL generated by solid i18n is correct but probably one of cms middlewares / redirect functions is changing the url .... adding language prefix ...

**Comment by mkoistinen** [comment]
Does anyone have a reference to what solid_i18_patterns is? I did a google search and all results lead back to here.

**Comment by yakky** [comment]
@mkoistinen i thin it refers to https://github.com/st4lk/django-solid-i18n-urls

**Comment by pawelmarkowski** [comment]
@mkoistinen: @yakky is right, this tool isquite simple and removing default language code from URL. I think URL's are quite problematic in django cms. It is a good idea to in the same step remove problem with:
1. if you change url of existing page you will receive 404 error - becouse system will not redirect you to the new address but stay at the same page (which was pernamently moved)
2. same like on 1st point will give you 404 after page removal (I think it should redirect you to main page)
3. When you move page in a structure as a child of another page system is for a long time giving wrong url (somewhere is stored old url)

**Comment by FinalAngel** [comment]
@mkoistinen any updates here on what to do?

**Comment by Aiky30** [comment]
Hello @pawelmarkowski,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
