### ISSUE TITLE
Templatetag "render_model_add" using properties from instance

### ISSUE THREAD

**Issue by helderco** [django-cms/django-cms#3897]
It would be cool to be able to create a new instance with some default property values in order to have these pre-filled in the popup dialog in the frontend.

```
# views.py
context['new_person`] = Person(category='Some category based on current view')

# template.html
{% render_model_add new_person %}
```

What do you guys think?

**Comment by bharling** [comment]
+1 For this from me, it would be really really useful for adding related models solely in the frontend. I had thought it would be nice to extend the template tag to accept context-aware kwargs ( exactly like django's url tag ). Any supplied kwargs would just supply initial context to the add form.

eg:

`{% render_model_add models.Picture category=context.category %}`

This would be really handy for me, I'd thought it should not be too hard to add but looking at the FE integration it seems it might be?

**Comment by Aiky30** [comment]
Hello @helderco, @bharling,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
