### ISSUE TITLE
Language chooser does not respect `hide_untranslated` setting

### ISSUE THREAD

**Issue by darbula** [django-cms/django-cms#3966]
Documentation states

> If hide_untranslated is True in your CMS_LANGUAGES and you are on a page that doesn’t yet have an English translation and you view the German version then the language chooser will redirect to /.

On page `/hr/subpage/` that has no english translation `{% language_chooser %}` displays:

```
<ul>
  <li class="cms_toolbar-item-navigation-active "><a href="/hr/subpage/"><span>hr</span></a></li>
  <li class=" "><a href="/en/subpage/"><span>en</span></a></li>
</ul>
```

The en link should be `/` but it is `/en/subpage/`.

`settings.py`:

```
CMS_LANGUAGES = {
    'default': {
        'public': True,
        'hide_untranslated': True,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'code': 'hr',
            'name': gettext('hr'),
        },
        {
            'code': 'en',
            'name': gettext('en'),
        },
    ],
}
```

**Comment by mkoistinen** [comment]
And if you go to `/en/subpage/` what happens?

**Comment by darbula** [comment]
Sorry for the delay, click on `/en/subpage/` goes to that url which makes 302 redirect back to `/hr/subpage/`, or from the user endpoint it just refreshes the same page.

**Comment by mkoistinen** [comment]
Hmmm, thanks for this. Looks like something needs to change.

**Comment by jlucchese** [comment]
Hello, any news on this subject?

**Comment by Aiky30** [comment]
Hello @darbula,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
