### ISSUE TITLE
PageField lists pages available in current user language instead of page languages

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#3981]
If you use a `PageField` in one of your plugins, then the only pages the user can link to are the pages that are in the same language as the preferred language of the user. The correct behaviour should be to put the pages that are in the same language as the page that is currently edited instead.

Here are the references in the code:
https://github.com/divio/django-cms/blob/38955c35a6e137343d5d1ecf5e355c38dce3f093/cms/forms/fields.py#L42
https://github.com/divio/django-cms/blob/38955c35a6e137343d5d1ecf5e355c38dce3f093/cms/forms/utils.py#L76

Claimed by @sephii

**Comment by sephii** [comment]
I started working on this here: https://github.com/sephii/django-cms/commit/1d2c875db1ce0c3ae9003b0aa6331e95215d82fe

I don't know what would be the right approach to get the language from the current page in the `PageField` though. Any suggestion?

**Comment by Aiky30** [comment]
Hello @sephii,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
