### ISSUE TITLE
django.views.i18n.set_language() compatibility

### ISSUE THREAD

**Issue by pa0lin082** [django-cms/django-cms#4050]
implementing the default django method  to  sets a user’s language preference (POST to django.views.i18n.set_language())
on a page of django-cms the request is ignored.

django.views.i18n.set_language() save the language preference in session[LANGUAGE_SESSION_KEY] and in browser cookie settings.LANGUAGE_COOKIE_NAME
In this case, the view cms.views.details does not properly recognize the language set.
Probably , language codes in url  (used in redirect) is the preferred choice in the definition of language to be applied

Contest :

Python 2.7.8
Django==1.7.1
django-cms==3.0.7

Note:
I installed django-cms under url "/cms" 
url(r'^cms/', include('cms.urls',None,'cms')),

**Comment by czpython** [comment]
As noted in https://github.com/divio/django-cms/issues/5776, this also affects the cache key.

**Comment by Aiky30** [comment]
Hello @pa0lin082,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
