### ISSUE TITLE
The menu modifiers system is brittle and arcane

### ISSUE THREAD

**Issue by lddubeau** [django-cms/django-cms#4099]
### The problem I was trying to solve

Suppose the following menu structure:
- "Section X" with url `/x`:
  - "A" with url `/x`
  - "B" with url `/x/b`

The parent node "Section X" shares with its child node "A" the same url. This may happen, for instance, when creating a `CMSAttachMenu` for an app that will be rooted at `/x` and for which we want to have the menu item titled "A" to serve as a way to return to the main page of this application. 

By default, the menu system bundled with Django CMS will never take node "A" as selected, because if two nodes have the same url, the first one wins the selection process, and the parent node will come first when `menus.menu_pool.MenuPool._mark_selected()` runs.

(Yes, I know I could work around the issue by having a _different_ url for menu "A", which would ultimately amount to the same thing as the url `/x`, but would make it so that Django CMS selects thenode I want. However, I do not want to multiply urls to work around Django CMS.)
### The solution I implemented and the issue I ran into

I wrote a custom modifier that would revise what `_mark_selected()` does. This is where problems started happening. To get the proper effect, it has to be executed before `menus.modifiers.Marker` runs. I managed to do that, but the order of the modifiers became:

```
[<class 'core.apps.SelectedModifier'>, <class 'menus.modifiers.Marker'>, 
 <class 'menus.modifiers.AuthVisibility'>,  <class 'menus.modifiers.Level'>, 
 <class 'cms.menu.NavExtender'>, <class 'cms.menu.SoftRootCutter'>]
```

The first modifier is mine. Not knowing what the correct order **must** be, it took me quite a while to figure out that `NavExtender` (maybe `SoftRootCutter` too??) should come before `Marker` (and my own modifier), otherwise `Marker` cannot do its job as it is working with a node tree with missing parent/child relationships.
#### The documentation

The above is really the short version of a long frustrating march towards figuring out what happens where exactly in Django CMS' menu system. Menu nodes know their relation to other nodes but they do not know this innately. It has to be set by the modifiers. There may be reasons for this that are obvious to those already intimate with Django CMS' internals but for someone approaching the issue from the angle of trying to integrate Django CMS' to an already existing application, it is far from obvious.

And the documentation, while helpful, is deficient. The issues:
1. The information about menus is spread indifferent locations:
   
   https://django-cms.readthedocs.org/en/3.1/introduction/menu.html
   https://django-cms.readthedocs.org/en/3.1/how_to/menus.html
   https://django-cms.readthedocs.org/en/3.1/topics/menu_system.html
   https://django-cms.readthedocs.org/en/3.1/reference/navigation.html
   
   (Plus API references but this is not part of the problem.)
   
   Why is this a problem? Let's suppose I visit [Customising navigation menus](https://django-cms.readthedocs.org/en/3.1/how_to/menus.html), which I did. I'd expect this section to provide everything needed for customizing navigation menus. There's a section on the modifiers. It explains what they are and how to create one and register it but there is no information regarding what the built-in modifiers do and the need to preserve their order. There is more information about the modifiers in  [another section](https://django-cms.readthedocs.org/en/3.1/topics/menu_system.html) but the customization section does not refer to it. So how is the reader to know that there's something else they really _must_ read? I understand the tutorial would not contain everything about menus. It is a _tutorial_, but perhaps the other sections could be collapsed? Or they should refer to one another. (Some links exist but not enough.)
2. [This section](https://django-cms.readthedocs.org/en/3.1/topics/menu_system.html) does mention the list of modifiers but does not say anything about what `NavExtender`'s task is, nor does it drive the point home that the **order matters** and that it is possible to end up with an incorrect order. (Yes, even if the apps are listed in the correct order in `settings.py`.)
#### The code

The code could be simplified so as to obviate the need for modifiers. `NavExtender` exists because `NavigationNode` instances don't always know who their parent is. This in turn calls for the existence of other modifiers (`Marker`, etc.) because they cannot do their job until the nodes all know where they are in the hierarchy, which cannot happen until `NavExtender` has run.

I've banged my head against the code long enough to know simplifying it is not a simple goal to achieve but it is a worthwhile one.

Or perhaps there could be a warning emitted if `cms.menu` finds that there is already another modifier installed before it registers `NavExtender` because there's a very high risk that the modifier installed before it won't work properly. I think it is the case that every single modifier that ships with Django CMS will fail to work properly if `NavExtender` is not first because they all rely on parent-child relationships.

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597, feel frea to continue the conversation here

**Comment by Aiky30** [comment]
Hello @lddubeau,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
