### ISSUE TITLE
Race condition in caching code

### ISSUE THREAD

**Issue by lddubeau** [django-cms/django-cms#4101]
Django 1.7
Django CMS 3.1.0

Just eyeballing the code in `cms/views.py`, it seems clear to me that the following scenario _can_ happen:
1. Worker A is executing `_cache_page()`. The version number it obtained when it executed `version = _get_cache_version()` is `N`. Its time slice ends just before executing `cache.set()`. The scheduler switches to Worker B.
2. Worker B is in the middle of serving a request that triggers a call to `invalidate_cms_page_cache()`. The cache version is incremented to `N+1`. Worker B finishes serving the request and waits for the next request. The scheduler switches to Worker A.
3. Worker A runs `cache.set()` with the version it obtained earlier: `N`. **And then sets the cache version to `N`**.

The cache version went from `N` to `N+1` and then back to `N`, annulling the cache invalidation, which means that now stale data is being served... at least until the cache entries expire.

I can produce the problem by adding `import time; time.sleep(10)` just before `cache.set()` in `_cache_page()` and performing a task that causes `invalidate_cms_page_cache()` to run.

Using `redis-cli` to repeatedly inspect the cache while the above is happening, this is what I see:

```
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
...
[the invalidation has happened]
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"11"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"11"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"11"
...
[_cache_page finishes]
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
redis redis.sock> get "!default:1:cms-CMS_PAGE_CACHE_VERSION"
"10"
```

(The exclamation point at the start of the key is a cache prefix added for my project.)

Granted the window of opportunity for the race condition is small, but it exists. Is this all moot for some reason I'm not aware of? 

It is not clear to me how the race condition should be fixed. In my own project, I've made my caching code dependent on Redis' atomic update facilities to avoid such problems. I doubt Django CMS should be made dependent on a single caching system. I thought about having `_set_cache_version()` check the current version and refuse to set the version to a number lower than the current one, but this only shifts the window of opportunity in which the race condition can happen. It does not eliminate it.

**Comment by mkoistinen** [comment]
Wow, nice sleuthing @lddubeau. Would it be enough to make the lines https://github.com/divio/django-cms/blob/develop/cms/views.py#L243-L253 more atomic? Something like this?:

```
import threading

...
ttl = get_cms_setting('CACHE_DURATIONS')['content']
with threading.Lock():
    version = _get_cache_version()
    cache.set(_get_cache_key(request), (response.content, response._headers), ttl, version=version)
    _set_cache_version(version)
```

@lddubeau since you apparently have a (local) test for this, could you give this a try?

**Comment by lddubeau** [comment]
@mkoistinen Unless I'm misremembering something about how `threading.Lock` works, this won't help if the application is running in a wsgi server that uses multiprocessing. Each process will have its own instance of a lock, invisible to others.

**Comment by fdik** [comment]
OK, actally WSGI does make lots of random errors here. Any idea how to setup django-cms so it can be used?

**Comment by Aiky30** [comment]
Hello @lddubeau 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
