### ISSUE TITLE
Wrong render of show_menu_below_id menu tag

### ISSUE THREAD

**Issue by bsenicar** [django-cms/django-cms#4228]
Hi, when I use show_menu_below_id tag in my page and want to show menu of pages which doesn't contain currently selected menu node menu is rendered improperly.

For example:
- Root
- \- Page1 <-- current page
- \- - Page11 <-- {% show_menu_below_id Page11_ID 0 100 0 1 %}
- \- - - Page111
- \- - - - Page1111
- \- - - Page112
- \- - Page12
- \- Page2

menu should be rended as:
- Page111
- Page112

But what I got is:
- Page111
- \- Page1111
- Page112

Problem is in cut_levels function in menus/templatetags/menu_tags.py, where if there is no selected node (as it is out of the scope in previous level) tree is not cut properly.

So I added the following code:

```
if selected:
    cut_after(selected, extra_active, removed)
+ else:
+     for node in nodes:
+        if node in final:
+             cut_after(node, 0, removed)
```

Best regards
Borut

**Comment by FinalAngel** [comment]
@mkoistinen can we implement this for 3.2?

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597

**Comment by Aiky30** [comment]
Hello @bsenicar,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
