### ISSUE TITLE
urlconf switching in tests unreliable

### ISSUE THREAD

**Issue by ojii** [django-cms/django-cms#4293]
# Overview

Our test suite relies on the ability to be able to safely and consistently switch between urlconfs (`ROOT_URLCONF`) in different test cases to test different scenarios. However this appears to not always work.
# Why we need to switch `ROOT_URLCONF` in tests

There's two main reasons for this:
1. Different styles of `ROOT_URLCONF`, this primarily means using `i18n_patterns` or not and mounting the CMS on `/` or not (historically we only tested the CMS mounted on `/`. it turned out it only worked that way so we added tests for it to be mounted on another URL)
2. Apphooks. Because of the way apphooked URLs work (and Django's URL system works), to test apphooks we need a clean urlconf (one that wasn't loaded yet). Apphook URLs unfortunately get hooked into the URL configuration on load (when `ROOT_URLCONF` is first imported), thus when testing apphooks and their URLs, we need an unimported `ROOT_URLCONF`.
# The Problem

In #4289 that, despite being used in two test cases, [NonRootCase](https://github.com/divio/django-cms/blob/819434e56745e4e6f597be7668c7572c9a9a67fa/cms/tests/nonroot.py#L15) and [ToolbarMiddlewareTest](https://github.com/divio/django-cms/blob/819434e56745e4e6f597be7668c7572c9a9a67fa/cms/tests/toolbar.py#L94), `cms.test_utils.project.nonroot_urls` only seems to be used in `NonRootCase` if both test cases are run in the same process, as shown by the fact that if it's imported (under Django 1.8), it raises an error if `CMS_APP_NAME` is set to a value other than `None`, which is why `NonRootCase` passes, but `ToolbarMiddlewareTest` doesn't.

If only `ToolbarMiddlewareTest` is run, the error occurs. If **before** running `ToolbarMiddlewareTest`, `NonRootCase` is run (in the same process), the tests pass. The loading off `nonroot_urls` in `NonRootCase` triggers caching of the module/urls, thus preventing subsequent calls to `override_settings(CMS_APP_NAME='foobar')` to actually do anything.

The result of the test case should be independent of the order of tests, which tests are run or which tests run in the same process.
# Reproduce

Run:

```
python develop.py test cms.tests.toolbar.ToolbarMiddlewareTest.test_app_setted_show_toolbar_in_cms_urls

python develop.py test cms.tests.nonroot.NonRootCase.test_get_page_root cms.tests.toolbar.ToolbarMiddlewareTest.test_app_setted_show_toolbar_in_cms_urls
```

The first will error, the second won't.

**Comment by timgraham** [comment]
Is the `ClearURLs` mixin in your branch meant to solve a different problem? `python manage.py test cms.tests.test_toolbar.ToolbarMiddlewareTest.test_app_setted_show_toolbar_in_cms_urls` still seems to have the same issue. That mixin seems redundant to me because of https://github.com/django/django/commit/65131911dba08dcc1451d71ae4d5101724d722f6. Was it needed only for Django 1.6?

**Comment by ojii** [comment]
It is supposed to fix this (and when I wrote it I was indeed working on fixes for 1.6), but it obviously doesn't fix it.

**Comment by timgraham** [comment]
Seems to be related to `sys.modules` caching. Have some ideas and will keep looking at it.

**Comment by ojii** [comment]
I found a possible fix/workaround: in ``setUpClass`` in ``ClearURLs``, after calling ``clear_url_caches`` check if ``settings.ROOT_URLCONF`` is in ``sys.modules``, and if it is, delete it.

**Comment by timgraham** [comment]
My idea is to listen to the `setting_changed` signal and clear the necessary URL modules if `ROOT_URLCONF` or any of the settings that affect it change.  Of course the urlpatterns need to be fixed too so they are passing an `app_name` without a `namespace`.

**Comment by ojii** [comment]
that sounds like a sane approach. 

Ignoring the caching issue, what's the actual fix for the include?

**Comment by timgraham** [comment]
I guess `app_name` could be removed (since it's unused when the test passes) or else a `namespace` should be added to `include()`. By the way, there is also a bad example in the docs: opened https://github.com/divio/django-cms/issues/4339.

**Comment by FinalAngel** [comment]
@ojii do we have a fix here or can it be closed?

**Comment by timgraham** [comment]
I believe one action item is to remove the `ClearURLs` mixin once support for Django 1.6 is removed.

**Comment by Aiky30** [comment]
Hello @ojii,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
