### ISSUE TITLE
about Page.template and TEMPLATE_INHERITANCE_MAGIC

### ISSUE THREAD

**Issue by jedie** [django-cms/django-cms#4303]
Fist: It seems that "Inherit the template of the nearest ancestor" doesn't exist in the documentation: https://github.com/divio/django-cms/search?utf8=%E2%9C%93&q=%27Inherit+the+template+of+the+nearest+ancestor%27

Then: The template inherit works like this:

```
    def get_template(self):
        template = None
        if self.template:
            if self.template != constants.TEMPLATE_INHERITANCE_MAGIC:
                template = self.template
            else:
                template = self.get_ancestors().template
        if not template:
            template = get_cms_setting('TEMPLATES')[0][0]
        return template
```

cleaned, pseudo code from: https://github.com/divio/django-cms/blob/c3056443f3c26a8973489b306875d12d13c54f5e/cms/models/pagemodel.py#L968-L988

What's about to insert one step before using **settings.TEMPLATES** ?
-> get the template from the page marked as "HOME":

![screen](https://cloud.githubusercontent.com/assets/71315/8832667/91936e32-30aa-11e5-934f-5a25726782d9.png)

This is the page with **is_home==True** isn't it?

The goal is: I must only change one page to set the template for the whole site.
Currently i have to change the template to all "root"-pages or change **settings.TEMPLATES**...

**Comment by yakky** [comment]
@jedie good point about documentation
Regarding the inheritance proposal, it defines a new magic and if I understand correctly a "by default magic", or do you mean to create a new "magic label" the user might choose?

**Comment by yakky** [comment]
@evildmp @mkoistinen what's your opinion?

**Comment by jedie** [comment]
I think the current algorithm is pretty useless.

Think another MAGIC is not a good idea. It will end in this two magic:
* Inherit template of nearest ancestor or use settings.TEMPLATE
* Inherit template of nearest ancestor or home page or use settings.TEMPLATE

This confusion, isn't it?
Maybe just say: **Inherit template** and the algorithm is:

* use self.template
* use template from nearest ancestor
* use template from home page
* use settings.TEMPLATE

As a work-a-round in the current solution:
```
index
|-- home
|-- page 1
|   `-- sub page
|-- page 2
|   |-- sub page
|   `-- sub page
`-- page 3
```
Where:
* **index** is non-visible and redirect to **/home**
* **index** sets a template
* all other pages used TEMPLATE_INHERITANCE_MAGIC

Now you can only change the template of **index** and all pages use the new template.
Other solution is to change settings.TEMPLATE, but you can't do this from the GUI and have to restart the server...



A other wish: Ability to temporary change the template for only one user
e.g.: To test a new template in "background" before switch to the new one.

**Comment by jedie** [comment]
Any news here?

**Comment by Aiky30** [comment]
Hello @jedie, 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
