### ISSUE TITLE
GlobalPagePermission in the Django Admin tries to load all Django users even with CMS_RAW_ID_USERS = True

### ISSUE THREAD

**Issue by LaurensBosscher** [django-cms/django-cms#4322]
Hi,

I've got a DB with ~84k users, while trying to edit the page permissions through the admin I can see in the slow query log that Django tries to get all users even when I've added "CMS_RAW_ID_USERS = True" to settings:
# Query_time: 8.327844  Lock_time: 0.000060 Rows_sent: 846227  Rows_examined: 846227

SET timestamp=1438086200;
SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user`;

Editing the page permission through the menu in the front end editor works without any problems and Django CMS seems to respect the CMS_RAW_ID_USERS setting there.

I thinkt his might be due to 'user' being in list_display and list_filter in GlobalPagePermissionAdmin (cms/admin/permissionadmin).

**Comment by Aiky30** [comment]
Hello @LaurensBosscher,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
