### ISSUE TITLE
CSRF token not set from cached pages as required

### ISSUE THREAD

**Issue by doctormo** [django-cms/django-cms#4330]
When CMS_PAGE_CACHE is true our website suffered a baffling intermittent error, where some users who were visiting the site for the first time could no log in (or use any forms) because they had no csrftoken cookie set.

I made a script to test the issue, making 100 requests to dev, staging and live deployments. dev and staging had no problems, but live would not set the csrftoken cookie for 80-95% of requests. I discovered that the DEBUG flag was the difference between them and found I could induce the issue on development by turning it off.

After a lot of digging I found the core of the issue at cms/views.py:54 onwards. What it's doing is checking to see if caching is enabled, checking to see if there is a cache of the page and then responding directly with the cached version.

One wrong solution was to allow the cache to cache the headers; but since the csrf token would be different for each user, it probably shouldn't be. I don't know what the right solution is for the cms codebase, but the workaround fix I've patched our live systems is here:

http://bazaar.launchpad.net/~inkscape-webadmin/inkscape-web/inkscape-web/revision/902

It's a middleware which introduces the CSRF_COOKIE_USED flag on every request. This Meta option isn't set on the cms cache because the template isn't rendered and thus {% csrf_token %} which would normally enable this flag is never called and the csrftoken is not added even if the csrf middleware is run.

**Comment by yakky** [comment]
Seems like the plugin with the login form does not set ``cache = False``

**Comment by doctormo** [comment]
There is no plugin with the login form. Is django-cms setup with the assumption that everything is a plugin and only cms things exist?

Because we have forms in base.html for login and we have app pages which aren't cms pages and the login has to be on both pages.

Plus, the cache really does help. The reason we didn't just switch it off was because we got a 10x increase in speed with the cache. According to the code I ready, the page cache is pretty all or nothing right?

**Comment by yakky** [comment]
@doctormo sorry I assumed the form was in a plugin. I'll give this a second look

**Comment by vstoykov** [comment]
The problem is that you cant have full page cache when you want to render CSRF token. This means that you need to disable cache which is not good.

We achieve this by hitting uncached URL which is decorated with from `django.views.decorators.csrf.csrf_protect`. This URL will set the correct CSRF cookie. If your form is not AJAX form then the hidden input value need also to be set from the JavaScript, by getting the value from the cookie. If you use also `CSRF_COOKIE_HTTPONLY = True` then your AJAX view decorated with `csrf_protect` need also to return the CSRF token value in order JavaScript to be able to get the right value.

**Comment by yakky** [comment]
@doctormo @vstoykov How about disabling CMS whole page cache and using django cache fragments? For content outside placeholders django CMS can only have an all-or-nothing approach, as the template rendering is entirely on the django side (see https://github.com/divio/django-cms/blob/develop/cms/cache/page.py#L29)
I don't see how django CMS can do anything here

**Comment by doctormo** [comment]
There certainly is something to be done about the issue. But I accept that you can make the choice between providing a fix for the full page caching so that it can deliver headers and exclude crsf tokens (complex) OR you can make the crsf token/the full page caching die in a horrible exception when it detects it's trying to cache the crsf token form. With a full explanation in the docs about what to do in this instance.

See I think there may be loads of developers suffering from this bug; it's just so intermittent and only effects you on your very first visit that I bet most of them aren't aware of the issue. An exception would provide a good way to alert them to the issue if you are not able to forge a solution.

**Comment by yakky** [comment]
@doctormo while we can skip the caching of the cookie header, the CSRF token in the page content can't be updated on every request, so even avoid caching the csrf cookie does not solve the issue at all.
But I'm open to any suggestion on how to fix the csrf cookie and the csrf field

**Comment by czpython** [comment]
As fate would have it, I'm quite familiar with this problem..
It's extremely difficult to reproduce and has no "nice" fix.

The problem with csrf tokens is something that a lot of systems with built-in caching face and as such I would argue that it's more or less outside of the scope of the system (django-cms in this case).
Having said that, it's a very annoying problem and so I'm all in for coming up with a fix.

I've solved this in two different ways in the past:

1. Turn off cms page caching **only** and make sure plugins that render forms are not cached.
By doing this I selectively cache placeholders/plugins but do not cache the whole page rendering logic which was fine for my project.

2. Turning off cache was not an option for a specific plugin because it was a plugin that required 4 levels of nesting (menu builder plugin) and it was rendered on every page using a staticplaceholder, so not caching this plugin would have impacted performance dramatically.

So I allowed the cms to cache the plugin (cache=true) and created the following template tag:

```python
@register.tag('render')
def do_render(parser, token):
    nodelist = parser.parse(('endrender',))
    parser.delete_first_token()
    return RenderTemplateNode(nodelist)

class RenderTemplateNode(template.Node):
    """
    The idea behind this tag is to render all text inside the {% render %} block
    using the current context and django's template framework.
    On normal circumstances this is not necessary and might seem useless,
    when used properly (ie. with {% verbatim %} tag), it allows us to not render certain blocks
    of code until template is rendered, this means if certain block is cached (like plugin content),
    then we can use {% verbatim %} to delay rendering of certain content and then {% render %} tag will
    actually do the rendering.
    """
    def __init__(self, nodelist):
        self.nodelist = nodelist

    def render(self, context):
        context['is_render_tag'] = True
        output = self.nodelist.render(context)
        return Template(output).render(context)
```

This template tag combined with {% verbatim %} allowed me to mark certain blocks of code in a template as "not cachable" so when the cms or django caches the template results, it will cache the template tags because of verbatim and then the {% render %} tag will re-render the template, thus rendering the cached template tags.

This solution is quite hackish but is the only way I found to mark certain content as "not cachable".

Instead of targeting csrf tokens, we should look for a solution like the one above that can be plugged into a template easily.

**Comment by doctormo** [comment]
I should add that the inkscape website can't possibly have full response caching because the login portion of the website (top right) displays the name of the user who is currently logged in. This isn't a cms plugin, just normal django base template work. That name is always different for different people. But the django form fails to work because the crfs token cookie is not sent when the cms page is cached. This is why our website was "fixed" with a middleware that forces the token to always be sent, the form isn't cached because it's outside of the cms page.

This is in my mind, in error. An assumption by the django-cms code about the nature of the base template which is not involved in caching. Unless of course the page caching is actually caching the whole response... but then that doesn't seem to be the case given the results we get.

**Comment by vstoykov** [comment]
@czpython your approach can lead to security problem. If portion of the page inside `{% render %}` block but outside `{% verbatim %}` is somewhat available for user input (form or something), it can inject django template tags (instead of html or javascript) and they will be executed. 
This heavily depends how your code is structured but still.

In general if you have full page caching you need to have some sort of middleware that will postprocess rendered content and replace parts of it with other parts. This is not panacea and can lead to security problems if it is not crafted correctly.

If you have dynamic content on the page which is specific for specific user but for him/her it stays relatively static (for example CSRF token - it is uniqe per visitor but stays the same for that visitor for a very long time), then caching need to rely somehow on that. Something like HTTP Vary header.

Probably in the CMS need to be added an ability to somehow mark plugins for cachable but for visitor. Then generated cache key need to be "salted" with information from cookies. And also HTTP Vary header to be set accordingly in order for caching proxies to not serve incorrect content to other users.

**Comment by mkoistinen** [comment]
CMS version 3.3.0.rc1+ introduces a new placeholder cache that accepts VARY headers from plugins. This issue here isn't due to plugin-caching, I see, but perhaps we can exploit the new VARY header support to solve this issue?

One way, would be to use a MW or a downstream cache to convert session cookies into an HTTP Header, then vary the cache on that header. Or at least to VARY based on whether the user is logged-in or not.

**Comment by Aiky30** [comment]
Hello @doctormo,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
