### ISSUE TITLE
no_signals not handled in Page.save()

### ISSUE THREAD

**Issue by LeGast00n** [django-cms/django-cms#4414]
Hi there,

The pre_delete_title signal handler for the Title model is calling the corresponding page's save() with no_signal=True.

However, the no_signal argument is not handled in the page's save() method, which may run to issues when a save signal handler is hooked onto the page model (given that it then may operate on a page that has just been deleted).

OK to let me fix that ?
Note: if so, can you advise on how I can get the latest version of the git repo synced on my end? (I still have the 3.2.0dev2 and I still suck with GIT...).

Thanks
LA

**Comment by Aiky30** [comment]
Hello @LeGast00n,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
