### ISSUE TITLE
Option to disable user settings for language

### ISSUE THREAD

**Issue by strindhaug** [django-cms/django-cms#4693]
But worse when using different domains/subdomains for the different languages the url is also wrong in the toolbar and uses the language code from the user settings to make prefix the urls (with a few random exceptions) causing 404 pages every time you use the toolbar.

I've set up a few localhost aliases in my /etc/hosts filefor norwegian, danish and swedish, and a middleware to switch language based on domain.

If I'm on the danish (da) page and the toolbar have stored norwegian (nb) in the user settings every menu item will use a url starting with `http://localdansk:8000/nb/` which doesn't exist since the the domain is danish.

Besides, it's really confusing when the toolbar is using a different language than the page you're editing. 

Please add an option to disable UserSettings (or at least the language settings in this object).

This issue is disappears if I don't use prefixed urls, using:

```
urlpatterns = patterns('',
```

instead of:

```
urlpatterns = i18n_patterns('',
```

But then the _caching doesn't_ work since neither the language code nor the host name is used in the cache prefix meaning you'll get a random language if multiple languages have the same path. (like the frontpage always will)

**Comment by Aiky30** [comment]
Hello @strindhaug,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
