### ISSUE TITLE
Toolbar javascript not compatible with django-compressor/sekizai

### ISSUE THREAD

**Issue by jsma** [django-cms/django-cms#4848]
I've had issues (see #4808) with the CMS CSS/JS where browsers will use the cached version of the files rather than the new versions after upgrading django-cms. 

I attempted to solve this problem by using django-compressor's post processor function on the sekizai tag. However, this leads to very incorrect results since https://github.com/divio/django-cms/blob/develop/cms/templates/cms/toolbar/toolbar_javascript.html contains dynamic variables. 

The variables change per request, so this leads to django-compressor generating a lot of *.js files that differ only in these variables. This causes issues because server 1 may generate the HTML containing the reference to this *.js but server 2 might answer the call and return a 404 since it doesn't have the generated file.The only quick fix for now is to disable post-processing the js block but then we're just back to the problem in #4808.

**Comment by FinalAngel** [comment]
We are looking into replacing the javascript initialisation using a JSON object rather than a JS instance. This is though, valid FE practice. I don't know too much about django-compressor functionality. @jrief has his fair share of knowledge, can you recommend a better path?

**Comment by Aiky30** [comment]
Hello @jsma,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
