### ISSUE TITLE
Scrollbar needed for pages overview in admin

### ISSUE THREAD

**Issue by Moini** [django-cms/django-cms#4981]
The new touch-enabled interface doesn't work well for me on a desktop.
In the pages overview, it needs zooming out to see all languages (I'd really like to know which pages have been translated) - and then the text becomes so small, that I can barely read it. 

A simple scroll bar that is available if on a not-touch-enabled, stationary device would be of great help.
(we might want to add additional languages)

Screenshots attached (Standard zoom, zoomed out to fit contents)

![bildschirmfoto_2016-02-04_22-29-29](https://cloud.githubusercontent.com/assets/3240233/12830344/10279e74-cb8f-11e5-9484-09347b863d34.png)

![bildschirmfoto_2016-02-04_22-29-45](https://cloud.githubusercontent.com/assets/3240233/12830337/075c4434-cb8f-11e5-80eb-3ff98f4e5d40.png)

Django 1.8.7., Django-cms 3.2.0

**Comment by czpython** [comment]
@vxsx was this fixed on 3.3?

**Comment by vxsx** [comment]
I have to check @czpython 
It's definitely scrollable horizontally with djangocms-admin-style, will have to check what happens without it

**Comment by Aiky30** [comment]
Hello @Moini,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
