### ISSUE TITLE
Documentation on extending/modifying menus is unclear

### ISSUE THREAD

**Issue by jsma** [django-cms/django-cms#5086]
In my project, I have 'root' level CMS pages that appear in the nav: Home and About. 

I now need to add a new item as a root level sibling, lets call it 'XYZ' which is not attached to a CMS page (for one reason, 'XYZ' isn't an actual page with content, only the sub menu items are clickable links). 

I statically extended the menu by subclassing `Menu`. My custom menu shows up but it will randomly appear before 'Home' or after 'About' (restarting the web server or runserver seems to be a coin toss where the menu item will appear). There is no obvious way from the documentation to control where this menu appears.

My next thought was, maybe I'm supposed to use a `Modifier` to control the order of menu items. 
The docs say "A modifier can change the properties of existing nodes or rearrange entire menus." but only shows examples of changing properties of nodes, not how to "rearrange entire menus".

Either way, my `Modifier` subclass appears to run before any of the built-in modifiers and it only ever receives a completely unordered and unorganized list of nodes. So its completely unclear how I'm supposed to take this random list of nodes and actually "rearrange" them.

@evildmp recommended the "Beginning django CMS" book on IRC, which I purchased. But its chapter on Menus and Navigation only mentions 'modifiers' once in the intro and never actually shows any examples at all of how to use them. In general, the book adds little info on this topic than what can already be found in the official docs (and inexplicably spends the later part of the Menus and Navigation chapter talking about sitemaps).

The problem for me is that the official docs seem to assume deep knowledge about the internals of how the menu system is implemented but little explanation is provided for 'how to use'. For example, we're told that the 'id' parameter is a "unique id for this menu". Ok. Should it be globally unique? Or just unique for the `Menu` subclass? How is this id used? How is the parent_id value used? How can I, as an end user of the public API, leverage these values to accomplish something?

The example for using a modifier just shows the implementation of the `Level` modifier. But again, there is no explanation of what `menu_level` vs `level` means or how its used to control anything, it's presented without comment.

In closing, would love to figure out how to control the ordering of my `Menu` subclasses without resorting to unnecessary `CMSAttachMenu` subclasses. If I ever gain enlightenment, I'll try my hand at a documentation patch but I feel pretty far from enlightenment on this topic at the moment.

**Comment by Aiky30** [comment]
Hello @jsma,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
