### ISSUE TITLE
With CMS_PUBLIC_FOR='staff' and DEBUG=False, admin-forwarding appears broken

### ISSUE THREAD

**Issue by maltebeckmann** [django-cms/django-cms#5091]
CMS_PUBLIC_FOR='staff' works as expected when I set DEBUG = True.
So when an author visits http://domain.com, he correctly gets redirected to http://domain.com/en/admin/login/?next=/en/admin/. That's what I need Django-CMS to do.

However, when I switch DEBUG = False and an author visits http://domain.com, then he doesn't get redirected to the admin login but rather incorrectly to http://domain.com/en/ which results in a "NOT FOUND The requested URL /en/ was not found on this server."
However, if he enters http://domain.com/admin, he is correctly forwarded to http://domain.com/en/admin/login/?next=/en/admin/ but I guess that's because of the admin regex catching that url before it gets forwarded to Django-CMS.

I doubt that CMS_PUBLIC_FOR is only meant to be used in debug mode.

The only item in my urls.py that changes in relation to DEBUG mode is `staticfiles_urlpatterns()`, which, according to the Django docs, is a helper function that will only work if DEBUG is True anyways. But that's static files related only, I guess.

I could understand if the CMS was to forward all non admin-url related requests to a static coming-soon page but such behavior is not outlined in the CMS docs, so I guess that can't be it either.

urls.py:

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import include, patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.http import HttpResponse
admin.autodiscover()


urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
    )

if settings.BLOCK_SEARCH_ENGINES:
    urlpatterns += (
        url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    )

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns  # NOQA

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += (
        url(r'^rosetta/', include('rosetta.urls')),
    )
```

**Comment by Aiky30** [comment]
Hello @maltebeckmann,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
