### ISSUE TITLE
Placeholder cache doesn't depend on URL

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#5565]
The plugins cache doesn't depend on the page URL, making it impossible to have a cached plugin that would behave differently based on the current page. A simple use case is a menu plugin that displays the menu of pages, with the current page having a specific class in the DOM (eg. `active`) to be able to distinguish it. The current caching system uses the same key across all URLs, thus using the same cached placeholder for all the pages and making this usecase impossible to implement.

The only solution at the moment is to use `cache = False` on the plugin, thus disabling the cache on the whole site (since all pages contain the menu plugin), which is very annoying.

Maybe we could have a mix between http://docs.django-cms.org/en/release-3.3.x/reference/settings-constants.html#cms-cache-prefix and https://docs.djangoproject.com/en/1.9/ref/settings/#key-function that would take a request as a parameter and returns a possibly altered cache key? This would then in turn be used here https://github.com/divio/django-cms/blob/release/3.3.x/cms/cache/placeholder.py#L90.

The issue appears on DjangoCMS 3.3.1, Django 1.9.8 and Python 3.4.

**Comment by czpython** [comment]
Hello,
We're aware of the issue, the solution boils down to having a plugin level cache.
Currently we have page and placeholder only.

With a plugin level cache, we wouldn't have a cache key per url every time.
Instead we give the control to plugin developers, this way in your case the plugin can return one cache key when it's active and another when it's not.

**Comment by tdsymonds** [comment]
Hello, 

I understand that this is quite an old issue but I find myself in a similar situation to @sephii, with a similar scenario to the menu plugin that has been described. If I change the `main_key` variable (see  https://github.com/divio/django-cms/blob/release/3.4.x/cms/cache/placeholder.py#L101-L108), to the below so that the cache key incorporates the url, then the problem is resolved for me. 

    main_key = '{prefix}|render_placeholder|id:{id}|lang:{lang}|site:{site}|tz:{tz}|v:{version}|u:{url}'.format(
            prefix=prefix,
            id=placeholder.pk,
            lang=lang,
            site=site_id,
            tz=get_timezone_name(),
            version=version,
            url=request.path,
    )

I assume there's a reason why the above approach won't work? @czpython, I'm not overly clear on your explanation, so apologies if I'm missing the point here.

It's frustrating as by setting the plugin to `cache=False` as @sephii explains renders the cache useless site wide. 

Is there an alternate way that this could work without updating the source code? If the caching with the url included is not applicable to all scenarios, could a plugin attribute not be utilised to tackle this? 

Thanks

**Comment by pierreben** [comment]
Hello,

Sorry to move up this old issue. 
The problem still occurs on last versions and can prevent some complex pages from being cached if they includes a plugin that can't use cache=True because of the placeholder cache key.
For example, when using some GET parameters in a plugin which results depends on those GET values, the plugin can't be cached.

Inspired by @tdsymonds 's comment, I solved the problem on several production instances by including a hash of the current URL in the cache key as implemented in this commit https://github.com/pierreben/django-cms/commit/3244eaeacadbfb6118215d5c8f1bbd15ddff6359.

Do you think that this fix can be integrated in a next release?
If not, do you know if there is another way of solving this issue?

Many thanks for your answers.
