### ISSUE TITLE
Identifiers generated for render_model_* tag containers are not unique per model

### ISSUE THREAD

**Issue by rafalp** [django-cms/django-cms#5677]
On my page I have two editable sections handled by two custom admin views:

```
{% render_model_block item "" "" "admin:products_product_advantage_change" %}
  // template with list of item's advantage objects
{% endrender_model_block %}
{% render_model_block item "" "" "admin:products_product_resource_change" %}
  // template with list of item's resource objects
{% endrender_model_block %}
```

However this results in both editable containes having same selectors:

```
  <div class="cms-plugin cms-plugin-products-product-claim-1 cms-render-model cms-render-model-block">
```

As well as registering two click handlers for every selector:

```
CMS._plugins.push(['cms-plugin-products-product-1', {
    ...
    edit_plugin: '/admin/products/product/1/change-advantages/?language=pl',

CMS._plugins.push(['cms-plugin-products-product-1', {
    ...
    edit_plugin: '/admin/products/product/1/change-resources/?language=pl',
```

This causes the double click event on any of frontend editable sections to fire two scripts, executing two ajax calls, canceling the first call and executing second one, giving me same modal no matter which section I'm trying to edit.

The custom url arg could've been md5'd and appended at the end of selector, producting sections like `cms-plugin-products-product-1-a897asd` and `cms-plugin-products-product-1-a8fha31d`.

**Comment by macolo** [comment]
I am surprised this doesnt affect apps like aldryn newsblog, aldryn jobs and the like. is `render_model` also affected or is the issue only with `render_model_block`?

**Comment by Aiky30** [comment]
Hello @rafalp,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
