### ISSUE TITLE
Creating Alias plugin between the pages of different language assigns the wrong language to Alias

### ISSUE THREAD

**Issue by Mimino666** [django-cms/django-cms#5774]
Scenario:

1. Page A is in English and has some plugins on it.
2. Page B is in Polish.
3. Create an Alias from some plugin on page A and paste it to page B.
4. The Alias will be pasted, but has English language set to it. It will be invisible, but still existing in DB.

**Comment by czpython** [comment]
Hello @Mimino666,

I'm unable to reproduce this.
I created an alias of a **plugin** from English and pasted it in German, the plugin rendered ok.
Creating an alias of a **placeholder** from English and pasting it in German results in only the german plugins being rendered from the aliased placeholder as expected.

**Comment by sephii** [comment]
I'm not sure about the following point:

> Creating an alias of a placeholder from English and pasting it in German results in only the german plugins being rendered from the aliased placeholder as expected.

It might be expected from a developer point of view, but, from a user point of view, creating an alias of a placeholder, pasting it in a different language and then seeing nothing appearing is very confusing (I actually had to look at the code to understand why the alias didn't get rendered).

It also means there's no way currently to have a static placeholder that is language independent (for example in my case a footer with sponsor images that are exactly the same in all ) that you can reuse accross languages without copying all the content manually, and updating it on every language every time you need to change it.

**Comment by Aiky30** [comment]
Hello @Mimino666,

The Alias plugin i being replaced by djangocms-alias in the near future.

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
