### ISSUE TITLE
When Title has not yet been saved, it should not offer a Publish button

### ISSUE THREAD

**Issue by evildmp** [django-cms/django-cms#5849]
### Summary

The publishing interface for Titles that have not yet been saved (i.e. for language versions of a page that don't yet exist) is confusing and throws a traceback if you try to use it.

### Expected behaviour

The Publish button should not throw a traceback.

### Actual behaviour

To replicate:

1. Create a Page in a site that supports multiple languages.
3. Switch to a language that has not yet been saved (i.e. give a title, slug, etc).
5. Hit **Publish**; a traceback will be thrown, whether or not any content has been added to the page's placeholders: ``DoesNotExist: Title matching query does not exist``.

<img width="1310" alt="screenshot 2017-01-16 12 35 08" src="https://cloud.githubusercontent.com/assets/86222/21984375/79524114-dbed-11e6-96cd-5014417c9b98.png">

Options for improving the interface:

* Disable the **Publish** button until the Title is saved.
* Optionally, disable editing of placeholders possible until the Title is saved.
* When **Publish** is used in this condition, it should open the _Page Settings_ modal dialog, to force saving the Title.
* Switching to a language without a saved Title should open the _Page Settings_ modal dialog, to force saving it.
* **Publish** should raise a friendlier error.

#### Environment

* Django version: 1.8.17
* django CMS version: 3.4.1

**Comment by czpython** [comment]
As decided in the board meeting, we won't show the "Publish" button if user has not configured the page translation.

@vxsx I've pushed a BE fix for this in https://github.com/divio/django-cms/pull/5884 but need FE to avoid showing the publish button when a plugin is moved, this logic is in js because the page is not reloaded. So we need to somehow tell the js that if the page has no translation then don't show that button.

**Comment by Aiky30** [comment]
Need to clarify if this has been resolved.
