### ISSUE TITLE
placeholder names with spaces: config will be ignored...

### ISSUE THREAD

**Issue by jedie** [django-cms/django-cms#6249]
e.g.:
```
{% placeholder "foo bar" %}

# ...

CMS_PLACEHOLDER_CONF = {
    "foo bar": {...}
```

In this case, the config will be ignored. Is this a bug or by-design?

If it's by-design, i would like to contribute a django system check to validate `CMS_PLACEHOLDER_CONF.keys()`

In my project i have this check:

```
@register()
def check_spaces_in_cms_placeholder_conf(app_configs, **kwargs):
    errors = []

    for key in settings.CMS_PLACEHOLDER_CONF.keys():
        if key is not None:
            key2 = slugify(key)
            if not key == key2:
                errors.append(
                    Error(
                        msg="Entry %r is not 'slugify'" % key,
                        hint="(The config will be ignored if the key contains spaces!)",
                        obj=settings,
                        id="CMS_PLACEHOLDER_CONF",
                    )
                )
    return errors
```

Don't know if a "slugify" key value is needed, but i think I'm gonna play it safe ;)

**Comment by czpython** [comment]
This is by design but I don't think it warrants a check on placeholder conf.
The reason being that the cms will slugify the slotname passed to the placeholder tag, so your conf will need to reference the slugified version of the placeholder slot name.

The ideal solution here is to deprecate passing anything that is not a slug to the placeholder tag.
This would eliminate some checks, as well as keep everything consistent.

**Comment by Aiky30** [comment]
Hello @jedie,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
