### ISSUE TITLE
Choices only available on first attribute

### ISSUE THREAD

**Issue by rprader** [django-cms/django-cms#6285]
### Summary

I have a custom CMSPlugin model with 5 attributes, each of them is an IntegerField with choices specified. The choices are always the same. When I edit the plugin in the frontend, only the first attribute is displayed as a dropdown with choices. The remaining ones only have a text field.

I'd expect, that all input fields should be displayed as a dropdown list. If I'd use different variable names for my choices, it works.

```
COLUMN_CHOICES = (((x, str(x),) for x in range(1, 13)))

class GridColumnPluginModel(CMSPlugin):
    cols_xs = models.IntegerField(verbose_name='Spalten XS', default=12, choices=COLUMN_CHOICES)
    cols_sm = models.IntegerField(verbose_name='Spalten SM', default=10, choices=COLUMN_CHOICES)
    cols_md = models.IntegerField(verbose_name='Spalten MD', default=8, choices=COLUMN_CHOICES)
    cols_lg = models.IntegerField(verbose_name='Spalten LG', default=8, choices=COLUMN_CHOICES)
    cols_xl = models.IntegerField(verbose_name='Spalten XL', default=8, choices=COLUMN_CHOICES)
```

### Environment

* Python version: 3.5
* (Aldryn-)Django version: 1.9.13.1
* django CMS version: 3.5.0.2

**Comment by czpython** [comment]
Hello @rprader,
Can you provide us with a screenshot of the issue?

**Comment by Aiky30** [comment]
Hello @rprader,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
