### ISSUE TITLE
Page.get_title_obj doesn't return correct title under certain conditions

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#6308]
### Summary

Calling `Page.get_title_obj` from a template on a page that has a title in french (configured to fallback to english) and a title in english, while viewing the page in french, will return the english title. This issue only happens if the page has an associated extension object (for example when using [this example code](http://docs.django-cms.org/en/latest/how_to/extending_page_title.html#title-model-extension-example)). 

The bug doesn't occur with DjangoCMS 3.4.5, and the issue seems to have been introduced by the removal of this line https://github.com/divio/django-cms/commit/f7af69f3e1#diff-960fbbc1702d77aa625a17bcb0c37191L1281. In my case the title cache only contains the french version of the page for as long as the page doesn't have any extension. As soon as I add an extension object, the cache then only contains the english version of the page, causing the call to `Page.get_title_obj` to use the english version of the page.

### Expected behaviour

`Page.get_title_obj` returns the page title in the current language.

### Actual behaviour

`Page.get_title_obj` returns the fallback language.

### Environment

* Python version: 3.4.2
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by czpython** [comment]
Hello @sephii,
Can you post your `CMS_LANGUAGES` setting?

**Comment by sephii** [comment]
Hi @czpython,

Here you go:

```
CMS_LANGUAGES = {
    'default': {
        'public': True,
        'hide_untranslated': True,
        'redirect_on_fallback': False,
    },
    1: [
        {
            'public': True,
            'code': 'fr',
            'name': _('French'),
        },
        {
            'public': True,
            'code': 'en',
            'name': _('English'),
        },
    ],
}
```

**Comment by czpython** [comment]
Thanks @sephii.
I've tried reproducing the issue using the exact settings you posted, as well as the title extension from the docs.

Here's a snippet from the template I used for testing:

```
{% extends "fullwidth.html" %}

{% block title %}{{ request.current_page.get_title_obj }}{% endblock title %}
```
How are you calling `get_title_obj`?

**Comment by czpython** [comment]
Ping @sephii

**Comment by mekanics** [comment]
Hey @sephii,
where you able to solve this problem. I'm currently having the exact same issue.

**Comment by sephii** [comment]
Hey @mekanics @czpython, I've been very busy since I reported this issue and didn't have time to dig further, but it's on my todo list!

**Comment by madEng84** [comment]
Same problem here.
I don't understand why he tries to get the page from title_cache instead of getting the one from the db

Step to reproduce the problem:

1. Create an english page "contacts"
2. Update the page "contacts" in an other language (ex. "contatti" in 'it')
3. Publish them
4. Create an english subpage "work-with-us"
5. Update the page "work-with-us" in an other language (ex. "lavora-con-noi" in 'it')
6. Publish  "en" version
7. Go to `en/contacts/work-with-us`
8. Go to `it/contacts/work-with-us`

### **Expected behaviour:** 

302 to `it/contatti/lavora-con-noi`### **Actual behaviour :** 

200 Response 

### **Environment**

django-cms==3.5.2
Django==1.11.15
python==3.6.5


N.B.

I wrote some [tests](https://github.com/divio/django-cms/files/2474102/tests.py.txt) to check this behaviour (see attached file)
2 tests raises, but maybe it is logically ok..

Hope it Helps
