### ISSUE TITLE
Issue deleting placeholder instances in App Model

### ISSUE THREAD

**Issue by crivet** [django-cms/django-cms#6313]
### Summary

I'm encountering a problem with using signals to delete placeholder instances in app models.

Essentially I'm utilizing a 'PlaceholderField' to allow users to populate the content of what is going to be an online textbook with different types of sections, etc. But for the sake of example i'll provide a simplified sample of what i'm trying to achieve:

After my previous contact with you guys, i was instructed on how to clear any plugin data from an instantiated model prior to deletion. and told to call `[placeholder].clear()` & `[placeholder].delete()` prior to to deleting the model, so in an attempt to generalize the process, i set this up using pre_delete signals as follows:

Models.py
```

 class SimplifiedCase(models.Model):
         
     #... fields/methods ...
    content = PlaceholderField('reading_content')  # ****** the placeholder 

    #define local method for clearing placeholderfields for this object 
    def clear_placeholderfields(self):
        # remove any child plugins of this placeholder
        self.content.clear()

        # remove the placeholder itself
        self.content.delete()  
        

#[in signals.py] create a generalized reciever (expecting multiple models to contain placeholders so generalizing the process)
def clear_placeholderfields(sender, instance, **kwargs):
    instance.clear_placeholderfields()  

# link the reciever to the section
signals.pre_delete.connect(clear_placeholderfields, sender=SimplifiedCase)

```
This is how i would expect to handle the deletion of the placeholder, but implemented as above as it triggers a recursion loop which continues calling 'clear_placeholderfield' until python throws an error, which seems odd being that it's calling `delete()` on a Placeholder, not the parent Model class.

Can anyone provide a little guidance on how to properly generalize the deletion placeholder instances from an app model? (under the assumption that multiple models will contain them)

### Expected behaviour
Calling the `[placeholder].delete()` method on the placeholder from within pre_delete should delete the instance from the cms_placeholder table prior to deletion of the model. 

### Actual behaviour
I'm getting a recursion loop if i call `placeholder.delete()` from within the pre_delete signal of the parent model.

### Environment

* Python version: 3.6.3
* Django version: 1.11.7
* django CMS version: 3.4.5

**Comment by crivet** [comment]
digging a little deeper into this one, it looks like the reason for the recursion is due to a `Placeholder` instanced by a `PlaceholderField` is not recognizing that it has a parent. 

Thus, being that placeholders don't have a delete method of their own and rely on the base `django.db.models.Model` delete method, when `placeholder.delete()` is executed:
- the method runs the collector for the placeholder to get any parents/related fields
- django gets a list of objects related to the placeholder. which will include the parent object (the `SimplifiedCase` model in this case (which is not actually a parent in the eyes of the collector... sad really)
- collector calls its `delete` method which loops over each instance in the collection
- this sends out the `pre_delete` signal again when it gets to the `SimplifiedCase` instance in the collection

My thinking was that specifying `placeholder.delete(keep_parents=True)` would have corrected this, but being that it's not actually seeing the model that instantiated the `Placeholder` field as a parent, this had no effect.

**Is there a way to trigger this delete method and have it know that a `Placeholder` instance has a parent?** 

I feel that there needs to be a way for this to happen, to avoid instances of deleting the parent containing the `PlaceholderField` and having the placeholder instance remain in the database. essentially adding in a data-leak for every model that contains a `PlaceholderField` 

attaching to a `pre_delete` signal seemed like the best approach to avoid having to override every model, and then having to worry about bulk deletions not calling the model's overridden delete method. (django's optimization feature)

**Comment by Aiky30** [comment]
Hello @crivet 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
