### ISSUE TITLE
Strange issue with Page.objects.search on two systems. (works on one, doesnt other)

### ISSUE THREAD

**Issue by gyoza** [django-cms/django-cms#6361]
### Summary

Page.objects.search(q="thing")

### Expected behaviour

Return page objects with "thing" in title.

### Actual behaviour

Works on Dev environment,

Get all pages with "thing" in title.

Move code to production environment and we get this:

```

get_latest/cms_plugins.py", line 52, in return_pages
    all_pages = Page.objects.search(q="thing")

  File "/opt/venv/env/local/lib/python3.6/dist-packages/cms/models/managers.py", line 83, in search
    qs = qs.filter(qt | qp)

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1251, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1271, in _add_q
    current_negated, allow_joins, split_subq)

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1277, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,

  File "/opt/venv/env/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1198, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))

FieldError('Related Field got invalid lookup: name',)

```

### Environment

* Python version: 3.5.2 (on both)
* Django version: 1.11.12 (on both)
* django CMS version: 3.5.2 (on both)

Any guidance would be extremly helpful, unsure what is going on here... Tried switching databases and having the same issue... models.py matches on both systems..

I've also tried blowing away the venv and reinstalling from scratch which does not seem to help either..

**Comment by Aiky30** [comment]
Hello @gyoza,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
