### ISSUE TITLE
AttributeError: 'module' object has no attribute 'allowed_elements' 

### ISSUE THREAD

**Issue by afs2015** [django-cms/django-cms#6401]
### Summary

I was following the Django CMS tutorial and received this error after logging into the admin for the first time and creating a new page. My virtual environment was activated and this was while python manage.py runserver has localhost up on http://127.0.0.1:8000/.

AttributeError: 'module' object has no attribute 'allowed_elements' 

### Expected behaviour

That a new page is created with copy in the Content once I hit the "Create" button.

### Actual behaviour

Hitting the "Create" button throws an AttributeError, [here is a traceback](https://hastebin.com/pekoyedagi.sql) for more details.

### Environment

* Python version: 2.7.10
* Django version: 2.0
* django CMS version: 3.5
* Operating System: OSX

**Comment by afs2015** [comment]
I'm going to keep this issue open but I figured out a workaround and I think the installer is having issues related to this: https://github.com/divio/djangocms-text-ckeditor/commit/175a1a444de8ca1ba4742196cb83150d45b5c505

The workaround was I had to `pip uninstall html5lib`  and then `pip install html5lib` which put html5lib 1.0.1 which appears to work.

**Comment by afs2015** [comment]
Issue has been addressed by the djangocms-installer project.

**Comment by fabiomolinar** [comment]
I just installed django-cms with its installer yesterday and I am getting the same error. I am using python 2.7. Below a list of the versions I am using:

- dj-database-url==0.5.0
- **Django==1.11.16**
- django-classy-tags==0.8.0
- **django-cms==3.5.2**
- django-filer==1.3.2
- django-formtools==2.1
- django-mptt==0.8.7
- django-polymorphic==2.0.3
- django-sekizai==0.10.0
- django-treebeard==4.3
- djangocms-admin-style==1.2.9
- djangocms-attributes-field==0.4.0
- djangocms-column==1.9.0
- djangocms-file==2.0.3
- djangocms-googlemap==1.2.0
- djangocms-installer==1.0.1
- djangocms-link==2.1.2
- djangocms-picture==2.0.7
- djangocms-snippet==2.0.0
- djangocms-style==2.1.0
- djangocms-text-ckeditor==3.6.1
- djangocms-video==2.0.5
- easy-thumbnails==2.5
- html5lib==0.9999999
- Pillow==5.3.0
- pytz==2018.7
- six==1.11.0
- tzlocal==1.5.1
- Unidecode==0.4.21

**Comment by fabiomolinar** [comment]
Could someone please re-open this issue? I don't think it has been fixed. Although the workaround (to uninstall and install html5lib) still works.

**Comment by aufdenpunkt** [comment]
I'm getting this error too since a couple of days. Is there any workaround to solve this issue? `pip uninstall html5lib` and `pip install html5lib` doesn't solve it for me 😞 

Which version of `html5lib` should be installed?

**Comment by fabiomolinar** [comment]
1.0.1 (which I believe is the latest) worked for me.

Yours sincerely,

*Fábio Thomaz Molinar*


Em qua, 14 de nov de 2018 às 23:54, Christian J. Schweinhardt <
notifications@github.com> escreveu:

**Comment by danieljkahn** [comment]
I am getting the same error. Installed using djangocms-installer.
Confirming also that the reinstall of html5lib does appear to solve the issue.

Package versions (after html5lib reinstall):
dj-database-url==0.5.0
Django==1.11.16
django-classy-tags==0.8.0
django-cms==3.5.3
django-filer==1.4.0
django-formtools==2.1
django-js-asset==1.1.0
django-mptt==0.9.1
django-polymorphic==2.0.3
django-sekizai==0.10.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-attributes-field==0.4.0
djangocms-column==1.9.0
djangocms-file==2.1.0
djangocms-googlemap==1.2.0
djangocms-installer==1.0.1
djangocms-link==2.2.1
djangocms-picture==2.1.1
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.6.1
djangocms-video==2.1.0
easy-thumbnails==2.5
html5lib==1.0.1
Pillow==5.3.0
pytz==2018.7
six==1.11.0
tzlocal==1.5.1
Unidecode==1.0.23
webencodings==0.5.1

**Comment by maholloway** [comment]
I'm also getting the same error and installed using djangocms-installer. The issue is fixed for me as well using the html5lib reinstall method above.

Package versions:
dj-database-url==0.5.0
Django==1.11.17
django-classy-tags==0.8.0
django-cms==3.5.3
django-filer==1.4.1
django-formtools==2.1
django-js-asset==1.1.0
django-mptt==0.9.1
django-polymorphic==2.0.3
django-sekizai==0.10.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-attributes-field==1.0.0
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-installer==1.0.2
djangocms-link==2.3.0
djangocms-picture==2.1.3
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-video==2.1.1
easy-thumbnails==2.5
html5lib==1.0.1
Pillow==5.3.0
pytz==2018.7
six==1.12.0
tzlocal==1.5.1
Unidecode==1.0.23
webencodings==0.5.1

**Comment by afs2015** [comment]
Reopening issue due to request from @fabiomolinar.

**Comment by Aiky30** [comment]
Hello,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
