### ISSUE TITLE
Documentation does not list support for Django 1.11

### ISSUE THREAD

**Issue by austin-carnahan** [django-cms/django-cms#6485]
### Summary

Documentation does not list support for Django 1.11 under 'Requirements' here:
http://docs.django-cms.org/en/latest/introduction/install.html

Noticed this after running the following in a python 2.7 virtual environment:
`djangocms -f -p . mysite`
`pip freeze`

```
...
Django==1.11.15
django-classy-tags==0.8.0
django-cms==3.5.2
...
```

**Comment by austin-carnahan** [comment]
I just realized you have this change implemented in the repo here:
https://github.com/divio/django-cms/blob/develop/docs/introduction/01-install.rst

but its not live on your site and leads to come confusing situations.

**Comment by Aiky30** [comment]
Hello @austin-carnahan 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this change we are unable to safely accept the contribution. If you feel this change is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
