### ISSUE TITLE
Missing feature in CMS_PLACEHOLDER_CONF: HTML before and after placeholder

### ISSUE THREAD

**Issue by python2and3developer** [django-cms/django-cms#6623]
I miss these attributes in CMS_PLACEHOLDER_CONF:
- before_html
- after_html

The content of `before_html` is rendered before the placeholder and only if the placeholder is not empty.
The content of `after_html` is rendered after the placeholder and only if the placeholder is not empty.

This way you can add a container or a wrapper to a placeholder and the container or wrapper is only added if the placeholder is not empty. For example, to add `<sidebar>`  and `</sidebar>` before and after the placeholder only if the placeholder contains plugins.

Do you think that this feature is interesting? If you think that it's interesting to include this to django-cms, I can help and create a branch.

**Comment by Aiky30** [comment]
Hello @python2and3developer,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
