### ISSUE TITLE
PageExtension Not Working 

### ISSUE THREAD

**Issue by mhavci** [django-cms/django-cms#6657]
Not migration table

Where am I doing wrong?

**models.py**

`
  from django.db import models
  from cms.extensions import PageExtension
  from cms.extensions.extension_pool import extension_pool

  @extension_pool.register
  class Person(PageExtension):

    name = models.CharField(max_length=100 , null=True)
    username_on_slack = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name  
`

**admin.py**

`
from django.contrib import admin
from .models import Person

from cms.extensions import PageExtensionAdmin

class PersonAdmin(PageExtensionAdmin):
	pass

admin.site.register(Person, PersonAdmin)

`

**cms_toolbars.py**

`
from cms.toolbar_pool import toolbar_pool
from cms.extensions.toolbar import ExtensionToolbar
from django.utils.translation import ugettext_lazy as _
from .models import SideBarExtension

@toolbar_pool.register
class SideBarExtensionToolbar(ExtensionToolbar):
    
    model = SideBarExtension

    def populate(self):
    
        current_page_menu = self._setup_extension_toolbar()
     
        if current_page_menu:
         
            page_extension, url = self.get_page_extension_admin()
            if url:
             
                current_page_menu.add_modal_item(
                        _('Sidebar'),
                        url=url,
                        disabled=not self.toolbar.edit_mode
                )

`

migrations

`

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=100, null=True)),
                ('username_on_slack', models.CharField(blank=True, default='SOME STRING', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='SOME STRING', max_length=254, null=True)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='core.Person')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
    ]

`
python manage.py makemigrations
python manage.py migrate

### Environment

* Python version: 3.7
* Django version: 2.1
* django CMS version: 3.6

**Comment by Aiky30** [comment]
Hello @mhavci,

It's not clear what you are trying to achieve.

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
