### ISSUE TITLE
Django cache framework not working with django-cms

### ISSUE THREAD

**Issue by rg2609** [django-cms/django-cms#6946]
I am using `django 3.1` and the [database caching][1] and it is working properly, but when I included the `django-cms` in the project and ran `python3 manage.py createcachetable` as per the document of the cache framework it's giving an error
```
 Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
 psycopg2.errors.UndefinedTable: relation "abc_cache_table" does not exist
 LINE 1: SELECT "cache_key", "value", "expires" FROM "abc_cache_t...
```
the cache table is getting created without django-cms, but not working with it. 
Is there any config that I am missing to add? any help and suggestion will appriated.

Thank you.

  [1]: https://docs.djangoproject.com/en/3.1/topics/cache/#database-caching

## Additional information
**Versions:**
Django-cms: 3.8
Django: 3.1
Python:3.6
aldryn-forms: [6.2.0.rc4](https://github.com/divio/aldryn-forms/releases/tag/6.2.0.rc4)

**Comment by marksweb** [comment]
Hi @rg2609 are you able to post the full error/stacktrace to hopefully show where CMS might be getting involved to cause this?

I've just ran this command on a project running CMS with django 2.2 and a project without CMS running django 3.2.

Both commands completed without any output or errors.

Also, on a side note because I didn't know this feature existed - what's the benefit of this? If I'm implementing a cache it's generally memcached or redis, and it's to prevent the database from being used.
