### ISSUE TITLE
Text plugin from django cms in the admin panel

### ISSUE THREAD

**Issue by zszep** [django-cms/django-cms#6970]
Is it possible to use the text plugin from django cms in the admin panel? I need some way to use some kind of html editor like the ckeditor in the admin panel. Preferably it would be ckeditor internally used from django cms for the text plugin. I have succeeded ckeditor showing instead of the standard input tag in the admin panel like this:

```
# models.py
class Post(models.Model):
    #content = models.TextField()
    content = HTMLField()
```
This is fine, but the plugins are not showing (e.g the picture plugin, file upload plugin).

**Comment by Aiky30** [comment]
@zszep this is not currently possible using djangocms-ckeditor because it is heavily reliant on the cms plugin system that requires a placeholder. 

There will be a ckeditor 5 package in the near future that will decouple the package from the cms plugin system. This package is still some way off but may be good to know.

**Comment by NicolaiRidani** [comment]
@victor-yunenko could your link to your CKeditor5 work?

**Comment by victor-yunenko** [comment]
Yes that would make sense to close in favour of the ckeditor5 integration, since it would be resolved once we're done with it. Here's the workgroup tech brief that contains the relevant details - https://hackmd.io/@django-cms/workgroup-ckeditor5
