### ISSUE TITLE
[BUG] Plugins with models that don't directly inherit from CMSPlugin or an abstract model cannot be copied

### ISSUE THREAD

**Issue by W1ldPo1nter** [django-cms/django-cms#6987]
## Description

If a plugin model inherits from another non-abstract plugin model (which is not `CMSPlugin` itself), its plugin instances cannot be copied on CMS pages. Instead, an error is raised.

## Steps to reproduce

1. Define a plugin model structure like this
```python
from cms.models import CMSPlugin

class Direct(CMSPlugin):  # non-abstract
    ...

class Subclass(Direct):  # non-abstract
    ...
```
2. Define a CMS Plugin that uses the `Subclass` model
3. Use an instance of said plugin on a page
4. Try to copy the instance in the structure panel
5. See error

## Expected behaviour

The plugin should be copied to the clipboard and should be able to be pasted somewhere else in the structure panel.

## Actual behaviour

An exception is raised while trying to copy, which originates [here](https://github.com/django-cms/django-cms/blob/release/3.8.x/cms/models/pluginmodel.py#L340):

```
AttributeError: 'CMSPlugin' object has no attribute 'cmsplugin_ptr_id'
```

## Additional information (CMS/Python/Django versions)

Python 3.8
Django==3.1.3
django-cms==3.8.0

Regarding the line that raises the error:
```python
            plugin_instance.cmsplugin_ptr = new_plugin
```

It appears that, even though the attribute is called `cmsplugin_ptr`, Django doesn't necessarily expect a `CMSPlugin` instance here (which `new_plugin` always is). Instead, Django seems to expect an instance of the closest ancestor (`Direct` in my example above), which would then also have `cmsplugin_ptr_id` attribute itself (hence the `AttributeError` above). This is also why the code works for models that inherit directly from `CMSPlugin` (or an abstract model), since `CMSPlugin` is the closest ancestor in this case.

A simple fix may be to set the `cmsplugin_ptr_id` instead - when dealing with the raw ID, the type of `new_plugin` doesn't matter. With the line above changed to
```python
            plugin_instance.cmsplugin_ptr_id = new_plugin.pk
```
copying plugins seems to work in all inheritance scenarios in a short test. I may be able to provide a PR utilizing that fix if the issue is accepted.

**Comment by jrief** [comment]
This btw. is bad practice. If `Subclass` inherits from `Direct`, then `Direct` should be abstract anyway. Otherwise you get far too many joins while querying the database.

**Comment by W1ldPo1nter** [comment]
Generally yes, although whether it becomes "far too many" joins or not highly depends on how complex the inheritance structure is. Having one submodel like in the example above would only lead to one more join, which may be acceptable performance-wise.

The bigger problem is that the full structure may not be under one's control entirely. For example, if there's some library that offers a CMS plugin and a corresponding model and I need to add only one or a few fields to it, then I have to hope that the library offers an abstract model as well. Otherwise my options are to either inherit from the non-abstract model, to do some weird extension via another model and a `OneToOneField` (boilerplate and the same join in the end) or to copy that model's code (even worse). That's why it would be nice if the inheritance approach would work, even if there are better alternatives for most cases.

**Comment by jrief** [comment]
I see your point. In general, it is possible to extend the structure below any plugin to whatever you link. Remember though, that then you have to duplicate those relation between the plugin attached to the "draft" page, when copying to the "public" page. This is described here in detail: https://docs.django-cms.org/en/latest/how_to/custom_plugins.html#handling-relations

– Disclaimer – I am the author of this library –
Because of exactly this problem, I created [djangocms-cascade](https://github.com/jrief/djangocms-cascade). There you can create a big inheritance tree for all of your plugins, even with multiple parents and mixins. But since the payload is stored in JSON, all of them share one Plugin Model for *all* Plugins. In this library I don't have any problems with handling the relationships.
If you don't like djangocms-cascade, try out [django-entangled](https://github.com/jrief/django-entangled) for the JSON part only.
