### ISSUE TITLE
[Developer Experience] Implement black as code formatter

### ISSUE THREAD

**Issue by vinitkumar** [django-cms/django-cms#7124]
To ensure the code looks consistent across all the files and remove all style related arguments from the code, I propose that we move to black as our official code formatter. Once decided, we also release instructions on how to configure it and even an example to add it as a pre-commit hook.

A lot of python projects and libraries have moved to black for formatting, and I think we should join the wagon too. I am curious to know  what everyone thinks about it?

**Comment by marksweb** [comment]
I'm yet to ever use black. I do see it used a lot though in OSS. Typically at work we've only ever been in fairly small teams so it's easy to get everyone to follow the same kind of structure.

I can see the benefit of it on projects like this though. Even if it might completely destroy my preferred coding styles 😆 

We could also put black and flake8 into pre-commit hooks so that they're being ran as people work rather than just when things hit github actions.
