### ISSUE TITLE
[BUG - djangoCMS 3.9.0] <li> markup disappears in source view in text plugin

### ISSUE THREAD

**Issue by crydotsnake** [django-cms/django-cms#7151]
## Description

If you add a text plugin and enter a markup for an icon in the source view, the markup disappears from the source view after you save and go back to the source view.

## Steps to reproduce

- add a text plugin
- switch to the `source` view, and add a markup: `<i class="fab fa-docker" style="text-align: center; color: #0397F5;"></i>`
- Save, and go back to the text plugin -> `source` view.

### Issue Video

https://user-images.githubusercontent.com/39345336/140643158-83990200-9131-40de-bf90-e4660a78c79b.mov

## Additional information (CMS/Python/Django versions)

I use the normal django-cms-quickstart project.

**Comment by marksweb** [comment]
My first guess would be that `i` tags aren't allowed so it gets stripped.

Would be worth checking the allowed tags.

**Comment by MacLake** [comment]
Almost. The problem is that CKEditor thinks that empty `<i></i>` tags don’t make sense and therefore removes it, but some frontend frameworks (ab)use them to display icons.

You need to configure CKEditor to allow empty `<i>` and maybe also `<span>`. My settings look like this (in the Django settings file):

```
# djangocms-ckeditor-settings additional configuration
# DOCS: https://github.com/divio/djangocms-text-ckeditor

CKEDITOR_SETTINGS: dict = {
    'stylesSet':
        'default:/static/js/addons/ckeditor.wysiwyg.js',
    'contentsCss':
        ['/static/semantic/semantic.min.css', '/static/conference.css'],
}
```

And in `static/js/addons/ckeditor.wysiwyg.js` I have a copy of the standard settings plus

```
/*
 * Extend ckeditor default settings
 * DOCS: http://docs.ckeditor.com/#!/api/CKEDITOR.dtd
 */
CKEDITOR.dtd.$removeEmpty.span = 0;
CKEDITOR.dtd.$removeEmpty.i = 0;
```

And then it works. Maybe we should change the default settings, as icons with empty `<i>`or `<span>` have become quite common.

**Comment by crydotsnake** [comment]
Thanks a lot for your comment! @MacLake ! :)
