### ISSUE TITLE
Python3.10 installation fail

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/django-cms#7203]
## Description

Remark: 
Well. Since you switched from django-installer to docker . Django-cms became absolutely non developer friendly. if before for developement needed to spend 1 second and see resuld now need to wait till build and publish docker container. 
Whole development with django cms became 10 - 30 times longer.  We really started to think to go to wagtail.
Issue:

Python3 on madjaro (python 3.10)

fresh installation fail on step compilation uwsgi because docker startup cannot live without uwsgi;

```
    /usr/bin/ld: plugins/python/python_plugin.o: in function `uwsgi_pyimport_by_filename':
    python_plugin.c:(.text+0x1688): undefined reference to `PyParser_SimpleParseString'
    /usr/bin/ld: python_plugin.c:(.text+0x169d): undefined reference to `PyNode_Compile'
    /usr/bin/ld: python_plugin.c:(.text+0x1763): undefined reference to `PyParser_SimpleParseFile'
    /usr/bin/ld: python_plugin.c:(.text+0x1783): undefined reference to `PyNode_Compile'
    /usr/bin/ld: python_plugin.c:(.text+0x17ef): undefined reference to `PyParser_SimpleParseFile'
    /usr/bin/ld: python_plugin.c:(.text+0x180f): undefined reference to `PyNode_Compile'
    /usr/bin/ld: plugins/python/pyloader.o: in function `uwsgi_eval_loader':
    pyloader.c:(.text+0x172f): undefined reference to `PyParser_SimpleParseString'
    /usr/bin/ld: pyloader.c:(.text+0x174b): undefined reference to `PyNode_Compile'
    collect2: error: ld returned 1 exit status
    *** error linking uWSGI ***

```

## Steps to reproduce

trivial

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by macolo** [comment]
hi @jpVm5jYYRE1VIKL thank you for your report. 

regarding
> if before for developement needed to spend 1 second and see resuld now need to wait till build and publish docker container. Whole development with django cms became 10 - 30 times longer.

It's not relevant to your ticket but since you brought it up I would like to help. Docker is a great concept but sometimes it's a but counterintuitive. for django CMS to recompile you don't have to rebuild the docker image / container. If you run django CMS locally with ./manage.py runserver the runserver will reload as normal upon file changes. This should be more or less the same speed as with using a virtualenv on your host (if running on modern hardware). For this to work you have to mount your code into the docker container. For a state of the art setup please see https://github.com/django-cms/djangocms-template 

Of course if you would like to continue to run your django CMS barebone on your host using virtualenv you can continue to do so, please see https://docs.django-cms.org/en/latest/how_to/install.html

**Comment by marksweb** [comment]
Hi @jpVm5jYYRE1VIKL

We don't yet support python 3.10 from a pypi/pip package installation.

We're in the process of releasing django-cms 3.10 which does include support for python 3.10. So this will be available soon.

**Comment by crydotsnake** [comment]
Hello @jpVm5jYYRE1VIKL,

A few words from my side

As you may know, djangoCMS is an open source project. It lives on the dCA, and on the people who participate in the project. Anyone who wants to can participate in the djangoCMS project here. We are an open community, and absolutely any help is welcome.

djangoCMS is in no way not developer friendly. I can understand that it frustrates you that you are not getting anywhere with your problem. It can always happen that things do not work, because they are simply not supported yet. Like in your example. So it's also absolutely right that you create an issue on GitHub and ask for help. That's what the project lives on!. In your case, the solution could probably be to use Python 3.8 or Python 3.9 instead of Python 3.10.

**The djangoCMS Installer**:

The djangoCMS installer has been put on hold for now, as it currently installs an outdated version of dangoCMS. However, we are in the process of transferring the project to our organization for further development.

I hope you will solve your problem!

If you have any further questions or problems, feel free to join our [Slack](https://django-cms.org/slack)! :)

**Comment by vinitkumar** [comment]
@jpVm5jYYRE1VIKL Not sure if you are still subscribed to this thread, you might want to give `django-cms==3.10.0rc2` a try, it add python3.10 support and should just work. But we aware, 3.10.0rc2 is a release candidate and shouldn't be used in production yet.
