### ISSUE TITLE
[DOC] Install django-cms by hand instruction is incomplete

### ISSUE THREAD

**Issue by TiredFingers** [django-cms/django-cms#7236]
## Description

If you follow the instructions - this will lead to the installation of a broken version of django-cms, because 

`pip install django-cms`

will install django 4 as a dependency, which we don't support

* [x] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by crydotsnake** [comment]
We could change it to: `pip install django-cms==3.9.0` for a workaround.

**Comment by TiredFingers** [comment]
@crydotsnake or can add

`pip install django==3.2`

**Comment by marksweb** [comment]
> We could change it to: `pip install django-cms==3.9.0` for a workaround.
> 
> What do you think @marksweb ?

That wouldn't fix it because 2.2 or above are valid versions for cms 3.9.


@TiredFingers if we've got the "latest" docs version building off develop then it might be worth adding a note that Django 3.2 is recommended and that <4 is required.

The 3.10 release will enforce this though as it includes a change I made that (I think) made the requirement `>=2.2,<4.0`

**Comment by TiredFingers** [comment]
Good point, anyway cms is for developers, so we can think that they know what to do with our recomendations

**Comment by marksweb** [comment]
Closing this as I think we resolved it.
