### ISSUE TITLE
cms/toolbar/toolbar_javascript.html shows python and django version 

### ISSUE THREAD

**Issue by fbyaguar** [django-cms/django-cms#7270]
When we are logged in as CMS users and have access to the cms toolbar, the "toolbar_javascript.html" template source code shows version information of Django, Python, etc. I think this could lead to security issues. A good solution would be to hide this data for production when settings.DEBUG=False

![Screenshot from 2022-03-22 12-51-58](https://user-images.githubusercontent.com/84343507/159468888-ff06d71b-3994-443e-afb0-9d3435c5aaac.png)

django-cms==3.9.0

**Comment by DmytroLitvinov** [comment]
Hi djangocms team,

The whole conversation is about [that line](https://github.com/django-cms/django-cms/blob/9e8eb17497edf8f40d68f7dcb53b1b2c3576313c/cms/templates/cms/toolbar/toolbar_javascript.html#L28).
Proposal is about adding hiding functionality with `debug` for [that line](https://github.com/django-cms/django-cms/blob/9e8eb17497edf8f40d68f7dcb53b1b2c3576313c/cms/templates/cms/toolbar/toolbar_javascript.html#L27)

**Comment by marksweb** [comment]
I'd consider that very low risk, but I see your point @fbyaguar.

I'd advice always turning `CMS_TOOLBAR_ANONYMOUS_ON` off, so that you only provide the toolbar to users that you trust.

To resolve, this would likely be a case of adding the debug setting into the available CMS context processors and making that line conditional on debug as @DmytroLitvinov suggests.

**Comment by DmytroLitvinov** [comment]
@marksweb , I am ready to provide PR. Can I prepare it so it will the reviewed, merged and release in next release?

**Comment by DmytroLitvinov** [comment]
@marksweb , prepared [PR](https://github.com/django-cms/django-cms/pull/7271).
