### ISSUE TITLE
[BUG] Unpublished page stays in menu when another language is still published.

### ISSUE THREAD

**Issue by lab360-ch** [django-cms/django-cms#7335]
## Description

When on a page with multiple language one language gets unpublished the menu entry in the unpublished languages is still visible on the public page.

The page only disappears from the menu when all the languages of the page are unpublished.

## Steps to reproduce

1. Create a Page with at least 2 languages
2. Publish all languages
3. Unpublish one language
4. In the unpublished language, the page is still visible in the menu.

## Expected behaviour

Unpublished pages should never be visible in the menu on the live page.

## Actual behaviour

Unpublished pages are still visible in the menu on the live page when another language of the page is still published.

## Additional information (CMS/Python/Django versions)

Python 3.7.7
Django 3.2.6 and 3.2.13
Django CMS 3.9.0 and 3.10.0

**Comment by marksweb** [comment]
Hi @lab360-ch 

Thanks for raising. Could you please include the details from your template of how you're displaying your menu?

**Comment by lab360-ch** [comment]
Hi @marksweb 

We use the normal `show_menu` tag

```
{% show_menu from_level to_level extra_inactive extra_active "cms_menus/main_sub_nav.html" "" "" child %}
```

cms_menus/main_sub_nav.html
```
{% load navigation_tags seo_tags %}

{% for child in children %}
    <li class="sub-nav-list__item">
        {% with url=child.attr.redirect_url|default:child.get_absolute_url %}
            <a class="sub-nav-item {% if child.selected %}sub-nav-item--selected{% endif %}" href="{{ url }}">
                <span class="sub-nav-item__text">
                    {{ child.get_menu_title }}
                </span>
            </a>
        {% endwith %}
    </li>
{% endfor %}
```
Is this information enough, or do you need more?

Best regards

Ralf

**Comment by marksweb** [comment]
@lab360-ch Just debugging this one again and I think I can see where this might be happening - and it's intentional if so.

In my example, I've got a Czech site that is configured with the following language settings;

```
   19: [  {  'code': 'cs',
             'fallbacks': ['en'],
             'hide_untranslated': False,
             'name': 'Czech',
             'public': True,
             'redirect_on_fallback': False}
```

The menu nodes for rendering the site are gathered in `CMSMenu.get_nodes()`.

Here's a screenshot of that happening;
<img width="770" alt="Screenshot 2022-06-16 at 11 34 23" src="https://user-images.githubusercontent.com/1461191/174052808-de79162c-b97b-4fdf-835b-2a840662412a.png">

If you've got a similar setup on the languages, using a fallback, then that's why you see the menu item still.

If you remove any fallback languages, then you should just see the results of the active language.

**Comment by lab360-ch** [comment]
Hi @marksweb 

If it's helpful for you, we can discuss the issue together in a Google hangout call

**Comment by lab360-ch** [comment]
Hi @marksweb 

Are they any information about the status of the ticket?

**Comment by marksweb** [comment]
@lab360-ch nothing new. This still needs more investigation into where the query is happening to return the unpublished page that you're seeing.

One thing that just occurred to me is there's no filter on the published status in the query  captured previously.

**Comment by lab360-ch** [comment]
Hi @marksweb 

Any news on the topic? Are there any info missing? Or are there some other things we can support you?
