### ISSUE TITLE
Upgrading from 3.10.0 to 3.11.0 lacking asgiref

### ISSUE THREAD

**Issue by Dxvid** [django-cms/django-cms#7390]
Recently upgraded an application from django-cms 3.10.0 to 3.11.0.
asgiref isn't included as a dependency so when adding django-cms 3.11.0 I had to manually add asgiref to requirements.txt for it to install.
Even after adding asgiref it won't run and the application throws an exception already here at the import from cms.models.pluginmodel:
"from cms.models.pluginmodel import CMSPlugin"

Let me know if I can help you by searching for clues about what causes the errors

**Comment by marksweb** [comment]
Could you include the full error you're seeing?

I'm running 3.11 in production with no issues. We also don't include asgiref as a requirement because it's up to the project using the application as to whether or not it uses ASGI or WSGI. So it's right that the necessary library is required by the project, and not the package.

**Comment by adrien-delhorme** [comment]
`asgiref` is imported here:

https://github.com/django-cms/django-cms/blob/63f421ae600840dd77d974583e4827650ac538da/cms/utils/permissions.py#LL5C6-L5C13

**Comment by fsbraun** [comment]
@adrien-delhorme Which Django version are you using. asgiref is a Django dependency, I believe.

**Comment by adrien-delhorme** [comment]
Thanks! My project was on Django 2.2 🤦‍♂️.

**Comment by vinitkumar** [comment]
@adrien-delhorme Is this issue resolved? If yes, you can consider closing this ticket.

**Comment by adrien-delhorme** [comment]
I can't close the ticket, I'm not the original poster 😄!
