### ISSUE TITLE
[BUG] in django-cms4 'hide in navigation in toolbar doesnt work gets 403

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-cms#7491]
## Description

[BUG] in django-cms4 'hide in navigation in toolbar doesnt work gets 403 forbidden.

```
Forbidden: /admin/cms/pagecontent/2/change-navigation/
[28/Jan/2023 13:33:26] "POST /admin/cms/pagecontent/2/change-navigation/ HTTP/1.1" 403 22
```

## Steps to reproduce

python==3.9
django==4.1.5
django=cms=4.1.0rc1

## Expected behaviour

Hides selected page from menu.

## Actual behaviour

Gives error.

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@svandeneertwegh This is **probably due to versioning**:

**Published version objects cannot be changed. Consequently, a PageContent object also cannot be shown or hidden in the navigation.**

The error message shown in the admin page is, however, somewhat cryptical as it indicates the user is missing the rights. **My suggestion would be to provide a better and clearer error message** if someone tries to change the publication status of a non-draft version.

To check if my assumption is correct create a new draft from a page and hide or show the draft in navigation.

**Comment by svandeneertwegh** [comment]
@fsbraun you'r right. When opening a page in draft mode the 'hide/show' in navigation works!

**Comment by fsbraun** [comment]
https://github.com/django-cms/djangocms-versioning/pull/317 now sends a meaningful error message.
