### ISSUE TITLE
[DOC] The suggested aldryn-search package does not work anymore with django>=4

### ISSUE THREAD

**Issue by fabien-michel** [django-cms/django-cms#7571]
## Description

https://docs.django-cms.org/en/latest/topics/searchdocs.html

The above documentation page suggest `aldryn-search` package which does not work anymore with django >4.0 (bug with Signal using `providing_args`) 
Since django-cms 3.11 is announced to be compatible with django 4 the documentation should no recommend to use this package.

* [ ] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by vinitkumar** [comment]
We should just switch the recommendation to django-haystack or something else, that is actively maintained. This is also true for all other `aldryn-*` packages, most of them are just not maintained anymore.

**Comment by fabien-michel** [comment]
The mention is still present in the online documentation

**Comment by pramitsingh0** [comment]
Hi team, I want to work on this issue.
I went through the documentation, so I need to remove aldrin search from it and link [django-haystack](https://github.com/django-haystack/django-haystack) in place of it. Is that correct?

**Comment by fsbraun** [comment]
It'll be great if you could include a working example.

**Comment by pramitsingh0** [comment]
> It'll be great if you could include a working example.

I haven't really used django haystack.

I was just going through your project for some inspiration on what I should build next and found something that seemed like a small thing in the issue section and thought may be I can contribute.

Though I will still try to add an example. According to what I understand haystack requires different search index backends like Solr, Whoosh etc right? So do I add the code for integrating different backends and Haystack in a project is that correct? Please let me know if I am wrong somewhere.

**Comment by fsbraun** [comment]
@pramitsingh0 I haven't used it either. Let's get it working together and collect feedback from some experienced people. Thanks for taking this up!!

**Comment by pramitsingh0** [comment]
> So do I add the code for integrating different backends and Haystack in a project is that correct?

Yeah sure, we can do that. Is this what we have to do?

**Comment by filipweidemann** [comment]
Is this still being worked on? Having a straightforward path to implement search is absolutely crucial for any CMS. I would even argue that this should come bundled with Django-CMS by default. To me it currently looks like there is not a single thing ready to be used to implement search. 

At least the aldryn-search functionality should be restored / made available asap. Maybe I could assist somehow?

**Comment by filipweidemann** [comment]
Okay, seems like contributions in here are probably dead.

@fsbraun would it be fine if I take a thorough look at `aldryn-search`, clean it up a bit, make it available as a new package (since the current one is archived) & add a section for the implementation into the main djangoCMS documentation?

We will probably need a dedicated package anyway since the internals of how the `PageContent` is laid out should be opaque to the average user imho so this would be the best path forward (if my opinion counts) ^^

Sorry to always bother you, but I don't currently know any other active maintainer. Would love a quick thumps up/down tho :)

**Comment by fsbraun** [comment]
@filipweidemann That would be wonderful! Please let me know if you have any questions!

**Comment by filipweidemann** [comment]
Yes, `django-haystack` seems well maintained and I'll keep using it just like `aldryn-search` did. It wasn't more than a pre-built haystack index anyway so I'll look there for inspiration and otherwise just stick with the approach and maybe trim it down a bit, seems like this would be the best approach for us currently.. and probably other users as well. 

You could theoretically install haystack and add an index for cms pages on a per-project basis, but I seriously think that having a package ready for that, including nice docs, seems like the most user friendly way to go and the project would really benefit from it again.

Other than that, no questions yet. I'll let you know when any come to mind :)
