### ISSUE TITLE
[feat] Without public home page, a 404 error is raised

### ISSUE THREAD

**Issue by fsbraun** [django-cms/django-cms#7763]
### Summary

If a root page has been created, but is not public (e.g., with djangocms-versioning), a 404 error is raised when the user tries to visit the root page.

While technically correct, a better user experience can be achieved by **redirecting the user to the page tree**. This is comparable with the user being redirected to a welcome page when no page object is present at all. 

### Expected behaviour

Either show the welcome page with an explanation (page has been created but is not public) or redirect to the `PageContent`'s changelist in the admin which shows the page tree and allows actions like preview or publish.

### Actual behaviour

404

### Environment

* django CMS version: 4.1.0

**Comment by erkesado** [comment]
@fsbraun, @marksweb let me fix this issue.

**Comment by erkesado** [comment]
To fix this issue, I added the following code to the `django-cms/cms/views.py` file:

```python
def details(request, slug):
    ...
    # version check
    current_content = PageContent.admin_manager.filter(page=page, language=request_language).last()
    current_version = current_content.versions.first().state
    if current_version != PUBLISHED:
        # current version is DRAFT, ARCHIVED, or UNPUBLISHED
        redirect_url = version_list_url(current_content)
        return HttpResponseRedirect(redirect_url)
    ...
``` 

As a result, the issue is gone and the program is working as expected.
Since the other test codes haven't used and considered the page versioning, other test codes are throwing errors because of my change. The test environment doesn't depend on and load the djangocms_versioning app either.

Before adding my change, the test run has 1 error and no failure.
![Screenshot from 2024-01-20 17-43-18](https://github.com/django-cms/django-cms/assets/18735647/220d7640-ab3c-4d86-80ba-d6de597ab54e)

After adding my change, the test run has 73 errors and 1 failure. I highlighted the error message in the image below.
![Screenshot from 2024-01-20 17-45-57](https://github.com/django-cms/django-cms/assets/18735647/89ad255b-8491-4e77-aa83-cc3aa13da4ab)

What am I doing wrong, guys? Should I fix the issue in the djangocms_versioning app instead of the django-cms app?
Or should I fix the issue without using the versioning feature (djangocms_versioning app)?

**Comment by fsbraun** [comment]
Hey @erkesado ! I think you are looking at the right spot. This `detials` view is quite complicated.

One thing is to be kept in mind. The django CMS core does not know anything about versioning. From the points of view of the core, the issue is that there is no content for the language. 

This is handled here:
https://github.com/django-cms/django-cms/blob/0f37d795627863712a09fd2eb2e764ebf3f6212b/cms/views.py#L134-L140

The function called is this:
https://github.com/django-cms/django-cms/blob/0f37d795627863712a09fd2eb2e764ebf3f6212b/cms/page_rendering.py#L56-L64

I believe the direct way of tackling the issue is to fix it in `_handle_no_page`. It knows the request and the path (`request.path`). You can check if that path belongs to the root page by resolving it and checking if the `url_name` of the resolved path matches the pages root view: `"pages-root"`. If so, I'd suggest redirecting to `reverse("admin:cms_pagecontents_changelist")`, which is the page tree.

This way you'd also have any non-versioning scenario captured, e.g. a user deleting all languages of the root page.

**Comment by erkesado** [comment]
Hi @fsbraun! Thank you very much. With your generous help, the issue has been fixed, and the related test codes have been added.
There is only 1 failure left in the test. In `cms/tests/test_static_analysis.py` file, the `test_ruff` fails and throws the following error:
```
self.assertEqual(os.spawnv(os.P_WAIT, ruff, ["ruff", "cms", "menus"]), 0)
AssertionError: 1 != 0
```
But how does it relate to my change in the code? Please, give me a clue :1234:

**Comment by fsbraun** [comment]
Try running `ruff cms --fix"`.

**Comment by fsbraun** [comment]
Ruff is the linter we use and the return code of 1 indicates that it found a linting issue.

**Comment by erkesado** [comment]
@fsbraun thanks again. I've installed the ruff extension on my VS code.

**Comment by fsbraun** [comment]
@erkesado Great work! Thank you! Can I ask you how you are doing with languages? There's some new strings to translate [for Chinese, for example](https://app.transifex.com/divio/django-cms/viewstrings/#zh_CN/core4/445320859).

**Comment by erkesado** [comment]
@fsbraun I don't know anything about Chinese. But I can do translations for Mongolian which is my native language. Mongolian is very different from Chinese and they have no similarities at all. But it is very similar to Turkish and they belong to the same language group, Altaic languages.

**Comment by erkesado** [comment]
@fsbraun can you close this issue?

**Comment by fsbraun** [comment]
@erkesado Sure! 

Mongolian is great, of course, but I fear there has not been done much. The more I would appreciate any time you spent on this. To make this feasible I would suggest not to go for 100% coverage in the first step...  Are you on our slack channel (https://django-cms.org/slack)?

**Comment by erkesado** [comment]
@fsbraun Yes, I'm on the slack channel.
I've seen the progress of Mongolian translation on Transifex.
The coverage is at the 1%.

**Comment by sakhawy** [comment]
Hello!
Since a redirection got introduced to ``_handle_no_page``, there's an interesting edge-case I encountered while working on another issue:
- Start with a new project
- Create a page, it will automatically get set to be the homepage
- Create another page
- Delete the homepage
- Try to go to the root
- You'll get an AttributeError: 'NoneType' object has no attribute 'is_home'

That's because on line 119 in cms.views, ``_handle_no_page`` is called but not returned and it won't raise a 404, it will return a redirect. Thus, the execution of ``detail()`` will continue
https://github.com/django-cms/django-cms/blob/ed7e2064e023c29b169084dd53a3b8643ac66715/cms/views.py#L116-L120

It will fail on line 134
https://github.com/django-cms/django-cms/blob/ed7e2064e023c29b169084dd53a3b8643ac66715/cms/views.py#L134

This can be solved with a simple return:
```python
    if not page:
        return _handle_no_page(request)
```

Another point, should a non-admin get redirected to ``/en/admin/cms/pagecontent/``? Isn't better to have a permission check and return a 404 if that check fails? Something like:
```python
        user_has_perm = user_can_change_page(
            request.user,
            get_page_from_request(request)
        )
        if (resolved_path.url_name == 'pages-root'
                and user_has_perm):
            redirect_url = reverse('admin:cms_pagecontent_changelist')
            return HttpResponseRedirect(redirect_url)
```

**Comment by fsbraun** [comment]
Well spotted! Interestingly, the original call in line 29 did have the return. Can you create a PR?

**Comment by sakhawy** [comment]
Sure! What about the permission thing?

**Comment by fsbraun** [comment]
What permission thing?

**Comment by sakhawy** [comment]
When an anon visits a non-existent root page they'll get redirected to the changelist. Is that desirable?

> Another point, should a non-admin get redirected to /en/admin/cms/pagecontent/? Isn't better to have a permission check and return a 404 if that check fails? Something like:

        user_has_perm = user_can_change_page(
            request.user,
            get_page_from_request(request)
        )
        if (resolved_path.url_name == 'pages-root'
                and user_has_perm):
            redirect_url = reverse('admin:cms_pagecontent_changelist')
            return HttpResponseRedirect(redirect_url)

**Comment by fsbraun** [comment]
Sorry, I did not see this. Its a call to make between two sides:
1. Inexperienced users might go back to their site without being logged in and still see the 404 (the correct check in that case would be `page_permissions.user_can_change_at_least_one_page`)
2. There might be an edge use case for the root CMS pages to purposefully raise a 404. I'd think that in such a case, the solution lies in catching the root CMS page in the `urls.py` and redirecting to the 404 view.

My call would be (2). @marksweb Do you have an opinion on this?
