### ISSUE TITLE
[BUG] Placeholder inherit raising "NoneType should implement get_template" if used on an apphooked page

### ISSUE THREAD

**Issue by aacimov** [django-cms/django-cms#7777]
## Description

Using Django CMS 4 upgraded from Django CMS 3.11.4. 

In a template from an apphooked page using `{% placeholder "Image rotator" %}` causes `NoneType should implement get_template` error. It is raised by `line 373, in get_declared_placeholders_for_obj`.

I must point out it happens on a page which does not have a parent but since it may be relocated to a subpage inheritance is needed because it should inherit the placeholder from parent if the one exists.

I have the old Django CMS 3 `PlaceholderField` in my custom's app models but it is not rendered in my list template where the issue arises. It should call a CMS placeholder not related to my app whatsoever (it is not defined in my models.py as a PlaceholderField).

I experience the same problem with another apphooked app's page **not having** the `PlaceholderField` in its `models.py`. It is however, strange, that in my other apphooked page the default template (list) renders as expected but the detail page raises the same error. Please note in my other app there is no `PlaceholderField`.

Using the inheritance in "regular" pages does not raise the error.

## Steps to reproduce

1. Create a page
2. Create an apphook on a created page
3. Make a default template for the apphook that extends `{% block content %}` from `base.html` and has a `{% placeholder "Image rotator" inherit %}` template tag (placeholded name does not matter)
4. When visiting the page the issue arises

## Expected behaviour

The page should inherit its parent page placeholder (show image rotator in my case).

## Actual behaviour

Placeholder from the parent page (if it exists) is not inherited, error arises, also if the page does not have a parent the result is the same - an error.

## Additional information (CMS/Python/Django versions)

Django CMS 4.1.0
Python 3.8.13
Django 4.2.9

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Hi @aacimov !

Indeed, in v3 you could use the page content placeholders in a root view of an apphook — although the page content was then called page title. While convenient, it was never a documented feature in v3, rather a lapse that was thankfully taken as a feature ;-)

In v4 this structurally is not possible, since you can only have one model with placeholders being edited in the frontend. You have two options:
1. Not have a view in the apphook for the root url and let django CMS fall back to the page content (only meaningful if you do not have apphook-specific content to present on the root url)
2. Have a view in the apphook but use the page content model for editing the placeholders. You will have to tell django CMS you want to access to page content model in the apphook's root view. This can easily be done by adding a few lines of code to that view (thanks to @jrief for the snippet):
```
def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.toolbar.edit_mode_active or self.request.toolbar.preview_mode_active:
            match = resolve(self.request.path)
            page_content = PageContent.admin_manager.get(id=match.args[1])
        else:
            page_content = self.request.current_page.get_content_obj()
        self.request.toolbar.set_object(page_content)
        if page_content:
            context['image_rotator'] = get_placeholder_from_slot(page_content.placeholders, slot='Image rotator')
        return context
```

You will have to use the.`{% render_placeholder image_rotator %}` template tag instead of the `{% placeholder %}` template tag. Additionally, the placeholder (“Main content” in the example) needs to appear in a `{% placeholder "Image rotator" %}` template tag on the page content's template.

Taking the extra step and clarifying what which toolbar object you actually want to edit makes integration with versioning possible.

Please let me know if that works for you.

**Comment by aacimov** [comment]
By looking at your code it should definitely work, although it was a great "easter egg" in v3 :) I realised why it doesn't throw an error on my other apphooked page. Because I have a CMS plugin rendering the list so it "respects" the parent placeholder inheritance. With the detail page it is just impossible (regarding your explanation) without overriding the get_context_data method.

Thank you so much for the explanation, closing the thread.
