### ISSUE TITLE
[ENHANCEMENT] Add RTL support for the pagetree

### ISSUE THREAD

**Issue by sakhawy** [django-cms/django-cms#7812]
## Description
The UI of the pagetree isn't as smooth in the RTL direction

## Expected behaviour
- The tooltip should be visible
- jsTree marker for drag-and-drop should start from the right to the left of the row (and shouldn't extend outside the container)
- The li drag-and-drop bg image should be on the right of the li
 

## Actual behaviour
As per the screenshots

## Screenshots
![Screenshot from 2024-02-14 17-33-48](https://github.com/django-cms/django-cms/assets/50373064/3fcbbaeb-7dab-436b-98ee-713afc883c61)
![Screenshot from 2024-02-14 17-34-11](https://github.com/django-cms/django-cms/assets/50373064/b336f316-e6df-479b-8de8-e852c2ade76a)
![Screenshot from 2024-02-14 17-35-24](https://github.com/django-cms/django-cms/assets/50373064/9870f6e2-a381-4272-84af-71cda1cedb1f)

## Additional information (CMS/Python/Django versions)

- django-cms==4.1.0
- django==5.0.1
- djangocms-admin-style==3.2.7

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@sakhawy I have not looked into this too much but my expectation would be

1. For the drag bar it is simply a matter of CSS: The drag handle is, in fact, a background image on the bar and positioned at the left. There is a rule missing moving it to the right. See line 833. To be on the right side, it would probably be `right center` instead of `-1px center`. (Also, I'd prefer `left center` to `-1px center`. If needed, we can crop the GIF by 1px): 
   https://github.com/django-cms/django-cms/blob/8a0aa59d91891c03d42d8a8d2752377a4306ec08/cms/static/cms/sass/components/pagetree/_tree.scss#L817-L835

2. For the dropdown menu, you'll have to think if you can solve it with CSS only. The relevant file is https://github.com/django-cms/django-cms/blob/develop-4/cms/static/cms/sass/components/pagetree/_dropdown.scss. There are two things to do: 
   1. Position the little triangle arrow on the other side of the dropdown. Now, there's three not well-named classes: `.cms-pagetree-dropdown-menu-arrow-top-right`, `.cms-pagetree-dropdown-menu-arrow-right-top`, and `.cms-pagetree-dropdown-menu-arrow-right-bottom`. Does it make sense to replace the "right" by "side" and change the CSS that it is right for ltr and left for rtl? This might also require some js changes.
   2. Position the dropdown aligned on the other side of the button:
 https://github.com/django-cms/django-cms/blob/8a0aa59d91891c03d42d8a8d2752377a4306ec08/cms/static/cms/sass/components/pagetree/_tree.scss#L407-L410

3. For the dragging I have not had time to look into it.

**Comment by sakhawy** [comment]
Thanks a lot for your helpful comment @fsbraun! I'm currently working on a PR (I'm at point 3 at the moment)

1. That was fixed. There's another reason why one might crop the GIF: there are a couple of padding pixels on the left -- I was leaving the decision of cropping it to the PR review.
2. I haven't taken a look yet but your approach makes sense. Thanks for the help. I'll get back to this issue if something doesn't make sense.
3. I think I have to do this from ``cms/static/cms/js/modules/cms.pagetree.js``. If you look at the ``_tree.scss`` file you can see that ``right: 3%`` is a hack(?). For example, try to resize the window and you'll see a slight change in the marker width relative to the tree container. If I have to do it in CSS then I need to hack my way around the width of the marker. The width of the marker isn't straightforward because jstree injects it into the body instead of the tree container for example. 

https://github.com/django-cms/django-cms/blob/8a0aa59d91891c03d42d8a8d2752377a4306ec08/cms/static/cms/sass/components/pagetree/_tree.scss#L1073-L1104

I'll try to do it from ``check_callback``.
https://github.com/django-cms/django-cms/blob/8a0aa59d91891c03d42d8a8d2752377a4306ec08/cms/static/cms/js/modules/cms.pagetree.js#L184-L194

**On another note**, how do you feel about using CSS logical properties (instead of explicitly setting left & right for example)?

**Comment by fsbraun** [comment]
Logical properties are even better. They keep the CSS smaller.

**Comment by sakhawy** [comment]
So far, 1 is fixed. As for 3, I managed to solve the problem by programmatically adding CSS to ``#jstree-marker`` on the ``dnd_move.vakata`` event -- the only event where this can work:
```javascript
            // styling the #jstree-marker dynamically on dnd_move
            var marker = $('#jstree-marker');
            var root = $('#changelist');

            marker.css({
                left: `${root.offset().left}px`,
                width: `${root.width()}px`
            });

        });
```

As I was working on this I noticed another part that needs RTL support (I think it's the grid I haven't looked into it yet):
![Screenshot from 2024-02-18 04-43-19](https://github.com/django-cms/django-cms/assets/50373064/fc4b5f7b-8c2d-4e89-906a-438ad12eb997)

Is it ok to put all of those fixes in the same PR?
